In [1]:
'''
This file plots CMIP5 RCP - HIST over South Australia
/Users/earl/Desktop/Yang
and places the outputs in
/Users/earl/Dropbox/CMIP5/figures

Earl Duran 
created: 19-Mar-18
e.duran@unsw.edu.au
'''

import os
import xarray as xr
import numpy as np
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import matplotlib
import sys
import pickle
import itertools
def find_nearest_index(array, value):
    return int((np.abs(array - value)).argmin())
from scipy import interpolate
from scipy import stats
from dask.distributed import Client

import cartopy.crs as ccrs
import cartopy.feature as cft
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
def arange(start,end,stride=1):
    return np.arange(start,end+0.00000001,stride)

import cosima_cookbook as cc
import sys, os
sys.path.append(os.path.join(os.getcwd(), '..'))  # so we can import ../exptdata
import exptdata
print('Available exptdata keys: ', [k for k in exptdata.exptdict.keys()])
session = cc.database.create_session()

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)


netcdf_index loaded.
Available exptdata keys:  ['1deg', '025deg', '01deg']


AttributeError: module 'cosima_cookbook' has no attribute 'database'

In [2]:
%%javascript
IPython.notebook.kernel.execute('nb_name = ' + '"' + IPython.notebook.notebook_name + '"')

<IPython.core.display.Javascript object>

In [3]:
client = Client()
client

<Client: 'tcp://127.0.0.1:42754' processes=4 threads=8, memory=33.67 GB>

In [4]:
# input_path = '/g/data/e14/erd561/NOAA_OI_SST_V2/'

output_path = '/g/data/e14/erd561/Australia_3/'

In [5]:
%%time
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='1deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

sea_level_z0_1_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='eta_t').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE))
print(sea_level_z0_1_mod_month)

sea_level_z0_1_mod_month.load()
print(sea_level_z0_1_mod_month)

xt_ocean = sea_level_z0_1_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
sea_level_z0_1_mod_month = sea_level_z0_1_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(sea_level_z0_1_mod_month)

sea_level_z0_1_mod = sea_level_z0_1_mod_month.groupby('time.year').mean('time')
print(sea_level_z0_1_mod)

sea_level_z0_1_mod = sea_level_z0_1_mod.sel(year=slice(1993+60*4,2017+60*4))
print(sea_level_z0_1_mod)

1deg_jra55v13_iaf_spinup1_B1


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: In xarray version 0.13 `auto_combine` will be deprecated.
  coords=coords)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset` to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in in future, please use the
new `combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  coords=coords)


<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 160, xt_ocean: 90)>
dask.array<shape=(3600, 160, 90), dtype=float32, chunksize=(1, 160, 90)>
Coordinates:
  * xt_ocean  (xt_ocean) float64 -269.5 -268.5 -267.5 ... -182.5 -181.5 -180.5
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * time      (time) object 1958-01-16 12:00:00 ... 2257-12-16 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t
<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 160, xt_ocean: 90)>
array([[[      nan,       nan, ..., -1.578523, -1.573317],
        [      nan,       nan, ..., -1.571597, -1.565494],
        ...,
        [ 0.506732,  0.498771, ...,  0.654748,  0.652205],
        [ 0.495682,  0.477471, ...,  0.642568,  0.640273]],

       [[      nan,  

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:160: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'eta_t' (year: 300, yt_ocean: 160, xt_ocean: 90)>
array([[[      nan,       nan, ..., -1.670531, -1.666994],
        [      nan,       nan, ..., -1.663988, -1.660291],
        ...,
        [ 0.479797,  0.487803, ...,  0.697266,  0.691195],
        [ 0.488086,  0.491912, ...,  0.694398,  0.68832 ]],

       [[      nan,       nan, ..., -1.676496, -1.67766 ],
        [      nan,       nan, ..., -1.664565, -1.665094],
        ...,
        [ 0.536418,  0.543263, ...,  0.690036,  0.685242],
        [ 0.54945 ,  0.551747, ...,  0.689748,  0.684691]],

       ...,

       [[      nan,       nan, ..., -1.801003, -1.79937 ],
        [      nan,       nan, ..., -1.795574, -1.793039],
        ...,
        [ 0.624408,  0.632264, ...,  0.690162,  0.68675 ],
        [ 0.636086,  0.638092, ...,  0.686346,  0.683252]],

       [[      nan,       nan, ..., -1.803916, -1.802256],
        [      nan,       nan, ..., -1.797055, -1.794382],
        ...,
        [ 0.615035,  0.622452, ...,

In [6]:
year = sea_level_z0_1_mod.year
lat_1_mod = sea_level_z0_1_mod.yt_ocean
lon_1_mod = sea_level_z0_1_mod.xt_ocean

sea_level_z0_1_trans_mod = sea_level_z0_1_mod
print(np.shape(sea_level_z0_1_trans_mod))
sea_level_z0_1_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='sea_level_z0_1')
sea_level_z0_1_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='sea_level_z0_1')
sea_level_z0_1_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='sea_level_z0_1')
for iid, i in enumerate(lat_1_mod):
    for jid, j in enumerate(lon_1_mod):
        sea_level_z0_1_slope_mod[iid, jid], _, _, sea_level_z0_1_p_value_mod[iid, jid], sea_level_z0_1_std_err_mod[iid, jid] = \
        stats.linregress(year, sea_level_z0_1_trans_mod[:, iid, jid])
    print('lat_1_mod ' + str(np.array(i)))
print(sea_level_z0_1_slope_mod)

(25, 160, 90)
lat_1_mod -69.6292858330716
lat_1_mod -69.17632154294074
lat_1_mod -68.70935410409521
lat_1_mod -68.22843658249317
lat_1_mod -67.73301847540898
lat_1_mod -67.2232002021303
lat_1_mod -66.69847936238045
lat_1_mod -66.15900514695375
lat_1_mod -65.60432451496254
lat_1_mod -65.03463652231858
lat_1_mod -64.44953841598465
lat_1_mod -63.84927987875662
lat_1_mod -63.233509039251814
lat_1_mod -62.602526632003375
lat_1_mod -61.95603192247815
lat_1_mod -61.29437678205883
lat_1_mod -60.61731152794955
lat_1_mod -59.92523891318751
lat_1_mod -59.21795988186098
lat_1_mod -58.49592747485757
lat_1_mod -57.75899250138302
lat_1_mod -57.00765736171395
lat_1_mod -56.24182163656275
lat_1_mod -55.46203582865502
lat_1_mod -54.66824687203264
lat_1_mod -53.86105179481633
lat_1_mod -53.04044315107174
lat_1_mod -52.20706260764199
lat_1_mod -51.36094630171701
lat_1_mod -50.50277835512628
lat_1_mod -49.63263616124607
lat_1_mod -48.751243830625256
lat_1_mod -47.858717411335334
lat_1_mod -46.9558182702592

In [7]:
%%time
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='025deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

sea_level_z0_025_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='eta_t').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE))
print(sea_level_z0_025_mod_month)

sea_level_z0_025_mod_month.load()
print(sea_level_z0_025_mod_month)

xt_ocean = sea_level_z0_025_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
sea_level_z0_025_mod_month = sea_level_z0_025_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(sea_level_z0_025_mod_month)

sea_level_z0_025_mod = sea_level_z0_025_mod_month.groupby('time.year').mean('time')
print(sea_level_z0_025_mod)

sea_level_z0_025_mod = sea_level_z0_025_mod.sel(year=slice(1993+60*4,2017+60*4))
print(sea_level_z0_025_mod)

025deg_jra55v13_iaf_gmredi6


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: In xarray version 0.13 `auto_combine` will be deprecated.
  coords=coords)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:783: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset` to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in in future, please use the
new `combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  coords=coords)


<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 475, xt_ocean: 360)>
dask.array<shape=(3600, 475, 360), dtype=float32, chunksize=(1, 435, 360)>
Coordinates:
  * xt_ocean  (xt_ocean) float64 -269.9 -269.6 -269.4 ... -180.6 -180.4 -180.1
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * time      (time) object 1958-01-14 12:00:00 ... 2257-12-14 12:00:00
Attributes:
    long_name:      surface height on T cells [Boussinesq (volume conserving)...
    units:          meter
    valid_range:    [-1000.  1000.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_t
<xarray.DataArray 'eta_t' (time: 3600, yt_ocean: 475, xt_ocean: 360)>
array([[[      nan,       nan, ..., -1.67311 , -1.671141],
        [      nan,       nan, ..., -1.671933, -1.669703],
        ...,
        [ 0.498718,  0.494208, ...,  0.676084,  0.676236],
        [ 0.485181,  0.4802  , ...,  0.667175,  0.668153]],

       [[      na

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:160: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'eta_t' (year: 300, yt_ocean: 475, xt_ocean: 360)>
array([[[      nan,       nan, ..., -1.71599 , -1.714387],
        [      nan,       nan, ..., -1.718057, -1.716083],
        ...,
        [ 0.465696,  0.468237, ...,  0.686613,  0.684455],
        [ 0.471382,  0.473248, ...,  0.683246,  0.681214]],

       [[      nan,       nan, ..., -1.723436, -1.720746],
        [      nan,       nan, ..., -1.726769, -1.723956],
        ...,
        [ 0.511942,  0.512129, ...,  0.664635,  0.662409],
        [ 0.518589,  0.518891, ...,  0.661631,  0.660411]],

       ...,

       [[      nan,       nan, ..., -1.787297, -1.785659],
        [      nan,       nan, ..., -1.789853, -1.787913],
        ...,
        [ 0.592735,  0.593659, ...,  0.652826,  0.650117],
        [ 0.598827,  0.599599, ...,  0.652331,  0.65008 ]],

       [[      nan,       nan, ..., -1.791817, -1.790245],
        [      nan,       nan, ..., -1.793794, -1.791964],
        ...,
        [ 0.561295,  0.561771, ...

In [8]:
lat_025_mod = sea_level_z0_025_mod.yt_ocean
lon_025_mod = sea_level_z0_025_mod.xt_ocean

sea_level_z0_025_trans_mod = sea_level_z0_025_mod
print(np.shape(sea_level_z0_025_trans_mod))
sea_level_z0_025_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='sea_level_z0_025')
sea_level_z0_025_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='sea_level_z0_025')
sea_level_z0_025_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='sea_level_z0_025')
for iid, i in enumerate(lat_025_mod):
    for jid, j in enumerate(lon_025_mod):
        sea_level_z0_025_slope_mod[iid, jid], _, _, sea_level_z0_025_p_value_mod[iid, jid], sea_level_z0_025_std_err_mod[iid, jid] = \
        stats.linregress(year, sea_level_z0_025_trans_mod[:, iid, jid])
    print('lat_025_mod ' + str(np.array(i)))
print(sea_level_z0_025_slope_mod)

(25, 475, 360)
lat_025_mod -69.98914896732052
lat_025_mod -69.8835503781156
lat_025_mod -69.77795178891068
lat_025_mod -69.67235319970577
lat_025_mod -69.56675461050085
lat_025_mod -69.46115602129593
lat_025_mod -69.35555743209102
lat_025_mod -69.2499588428861
lat_025_mod -69.14436025368119
lat_025_mod -69.03876166447627
lat_025_mod -68.93316307527135
lat_025_mod -68.82756448606644
lat_025_mod -68.72196589686152
lat_025_mod -68.6163673076566
lat_025_mod -68.51076871845169
lat_025_mod -68.40517012924677
lat_025_mod -68.29957154004185
lat_025_mod -68.19397295083694
lat_025_mod -68.08837436163202
lat_025_mod -67.9827757724271
lat_025_mod -67.87717718322219
lat_025_mod -67.77157859401727
lat_025_mod -67.66598000481235
lat_025_mod -67.56038141560744
lat_025_mod -67.45478282640252
lat_025_mod -67.3491842371976
lat_025_mod -67.24358564799269
lat_025_mod -67.13798705878777
lat_025_mod -67.03238846958286
lat_025_mod -66.92678988037794
lat_025_mod -66.82119129117302
lat_025_mod -66.7155927019681

lat_025_mod -30.778202070190314
lat_025_mod -30.56317292803898
lat_025_mod -30.34766755148325
lat_025_mod -30.131685174432455
lat_025_mod -29.915230577717967
lat_025_mod -29.698303070212805
lat_025_mod -29.480907483686703
lat_025_mod -29.2630432019257
lat_025_mod -29.044715107989248
lat_025_mod -28.82592266049411
lat_025_mod -28.606670794106993
lat_025_mod -28.38695904216067
lat_025_mod -28.166792391212045
lat_025_mod -27.946170449161986
lat_025_mod -27.72509825470525
lat_025_mod -27.50357549012893
lat_025_mod -27.28160724647727
lat_025_mod -27.059193280207044
lat_025_mod -26.83633873488693
lat_025_mod -26.61304344089147
lat_025_mod -26.389312594451354
lat_025_mod -26.165146099570944
lat_025_mod -25.940549205242547
lat_025_mod -25.715521888775697
lat_025_mod -25.490069451985352
lat_025_mod -25.264191945124278
lat_025_mod -25.037894722851966
lat_025_mod -24.811177907964588
lat_025_mod -24.58404690794839
lat_025_mod -24.356501917704698
lat_025_mod -24.12854839748857
lat_025_mod -23.90018

In [11]:
sea_level_z0_1_mod_xr = xr.DataArray(sea_level_z0_1_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='sea_level_z0_1_mod',
                        coords=[lat_1_mod, lon_1_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(sea_level_z0_1_mod_xr)
sea_level_z0_1_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_mod.nc')

sea_level_z0_1_slope_mod_xr = xr.DataArray(sea_level_z0_1_slope_mod, name='sea_level_z0_1_slope_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_1_slope_mod_xr)
sea_level_z0_1_slope_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_slope_mod.nc')

sea_level_z0_1_p_value_mod_xr = xr.DataArray(sea_level_z0_1_p_value_mod, name='sea_level_z0_1_p_value_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_1_p_value_mod_xr)
sea_level_z0_1_p_value_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_p_value_mod.nc')

sea_level_z0_1_std_err_mod_xr = xr.DataArray(sea_level_z0_1_std_err_mod, name='sea_level_z0_1_std_err_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_1_std_err_mod_xr)
sea_level_z0_1_std_err_mod_xr.to_netcdf(output_path + 'sea_level_z0_1_std_err_mod.nc')



sea_level_z0_025_mod_xr = xr.DataArray(sea_level_z0_025_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='sea_level_z0_025_mod',
                        coords=[lat_025_mod, lon_025_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(sea_level_z0_025_mod_xr)
sea_level_z0_025_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_mod.nc')

sea_level_z0_025_slope_mod_xr = xr.DataArray(sea_level_z0_025_slope_mod, name='sea_level_z0_025_slope_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_025_slope_mod_xr)
sea_level_z0_025_slope_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_slope_mod.nc')

sea_level_z0_025_p_value_mod_xr = xr.DataArray(sea_level_z0_025_p_value_mod, name='sea_level_z0_025_p_value_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_025_p_value_mod_xr)
sea_level_z0_025_p_value_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_p_value_mod.nc')

sea_level_z0_025_std_err_mod_xr = xr.DataArray(sea_level_z0_025_std_err_mod, name='sea_level_z0_025_std_err_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(sea_level_z0_025_std_err_mod_xr)
sea_level_z0_025_std_err_mod_xr.to_netcdf(output_path + 'sea_level_z0_025_std_err_mod.nc')

<xarray.DataArray 'sea_level_z0_1_mod' (yt_ocean: 160, xt_ocean: 90, year: 25)>
array([[[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [-1.804237, -1.79727 , ..., -1.801003, -1.803916],
        [-1.802819, -1.795696, ..., -1.79937 , -1.802256]],

       [[      nan,       nan, ...,       nan,       nan],
        [      nan,       nan, ...,       nan,       nan],
        ...,
        [-1.802441, -1.795215, ..., -1.795574, -1.797055],
        [-1.800091, -1.792714, ..., -1.793039, -1.794382]],

       ...,

       [[ 0.570624,  0.552581, ...,  0.624408,  0.615035],
        [ 0.572101,  0.553011, ...,  0.632264,  0.622452],
        ...,
        [ 0.660109,  0.63699 , ...,  0.690162,  0.736722],
        [ 0.655128,  0.632463, ...,  0.68675 ,  0.737148]],

       [[ 0.579468,  0.559259, ...,  0.636086,  0.624793],
        [ 0.574604,  0.554437, ...,  0.638092,  0.626524],
        ...,
        [ 0.654862,  0.