In [1]:
'''
This file plots CMIP5 RCP - HIST over South Australia
/Users/earl/Desktop/Yang
and places the outputs in
/Users/earl/Dropbox/CMIP5/figures

Earl Duran 
created: 19-Mar-18
e.duran@unsw.edu.au
'''

import cosima_cookbook as cc
import os
import xarray as xr
import numpy as np
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import matplotlib
import sys
import pickle
import itertools
def find_nearest_index(array, value):
    return int((np.abs(array - value)).argmin())
from scipy import interpolate
from scipy import stats
from dask.distributed import Client
import pandas as pd
from glob import glob as gb
import gsw

import cartopy.crs as ccrs
import cartopy.feature as cft
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
def arange(start,end,stride=1):
    return np.arange(start,end+0.00000001,stride)

import sys, os
sys.path.append(os.path.join(os.getcwd(), '..'))  # so we can import ../exptdata
import exptdata
print('Available exptdata keys: ', [k for k in exptdata.exptdict.keys()])

session = cc.database.create_session()

Available exptdata keys:  ['1deg', '025deg', '01deg']


In [2]:
%%javascript
IPython.notebook.kernel.execute('nb_name = ' + '"' + IPython.notebook.notebook_name + '"')

<IPython.core.display.Javascript object>

In [3]:
client = Client()
client

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/distributed/dashboard/core.py:72: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn("\n" + msg)


<Client: 'tcp://127.0.0.1:35248' processes=4 threads=8, memory=33.67 GB>

In [4]:
# input_path = '/g/data/e14/erd561/NOAA_OI_SST_V2/'

output_path = '/g/data/e14/erd561/Australia_3/'

In [5]:
%%time
lonW = 145-360
lonE = 175-360
latL = -34
ekey='1deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_yflux_adv_ym34_1_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='temp_yflux_adv').\
interp(yu_ocean=latL).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=slice(0,2100))
print(temp_yflux_adv_ym34_1_mod_month)

temp_yflux_adv_ym34_1_mod_month.load()
print(temp_yflux_adv_ym34_1_mod_month)

xt_ocean = temp_yflux_adv_ym34_1_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_yflux_adv_ym34_1_mod_month = temp_yflux_adv_ym34_1_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
st_ocean = temp_yflux_adv_ym34_1_mod_month.st_ocean
st_ocean_corrected = -st_ocean
temp_yflux_adv_ym34_1_mod_month = temp_yflux_adv_ym34_1_mod_month.assign_coords(st_ocean=st_ocean_corrected)
print(temp_yflux_adv_ym34_1_mod_month)

temp_yflux_adv_ym34_1_mod = temp_yflux_adv_ym34_1_mod_month.groupby('time.year').mean('time')
print(temp_yflux_adv_ym34_1_mod)

temp_yflux_adv_ym34_1_mod = temp_yflux_adv_ym34_1_mod.sel(year=slice(2004+60*4,2017+60*4))
print(temp_yflux_adv_ym34_1_mod)

1deg_jra55v13_iaf_spinup1_B1


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'temp_yflux_adv' (time: 300, st_ocean: 35, xt_ocean: 30)>
dask.array<getitem, shape=(300, 35, 30), dtype=float32, chunksize=(1, 25, 30), chunktype=numpy.ndarray>
Coordinates:
  * st_ocean  (st_ocean) float64 1.152 3.649 6.565 ... 1.854e+03 2.046e+03
  * xt_ocean  (xt_ocean) float64 -214.5 -213.5 -212.5 ... -187.5 -186.5 -185.5
  * time      (time) object 1958-07-02 12:00:00 ... 2257-07-02 12:00:00
    yu_ocean  int64 -34
Attributes:
    long_name:      cp*rho*dzt*dxt*v*temp
    units:          Watts
    valid_range:    [-1.e+18  1.e+18]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_c
<xarray.DataArray 'temp_yflux_adv' (time: 300, st_ocean: 35, xt_ocean: 30)>
array([[[            nan,             nan,             nan, ...,
          7.35225219e+10,             nan, -6.83562729e+11],
        [            nan,             nan,             nan, ...,
          1.14277867e+11,             nan, -7.1456

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [6]:
year = temp_yflux_adv_ym34_1_mod.year
depth_1_mod = temp_yflux_adv_ym34_1_mod.st_ocean
lon_1_mod = temp_yflux_adv_ym34_1_mod.xt_ocean

temp_yflux_adv_ym34_1_trans_mod = temp_yflux_adv_ym34_1_mod
print(np.shape(temp_yflux_adv_ym34_1_trans_mod))
temp_yflux_adv_ym34_1_slope_mod = xr.DataArray(
    np.zeros([np.shape(depth_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'depth_1', 'lon_1'), coords=[depth_1_mod, lon_1_mod], name='temp_yflux_adv_ym34_1')
temp_yflux_adv_ym34_1_p_value_mod = xr.DataArray(
    np.zeros([np.shape(depth_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'depth_1', 'lon_1'), coords=[depth_1_mod, lon_1_mod], name='temp_yflux_adv_ym34_1')
temp_yflux_adv_ym34_1_std_err_mod = xr.DataArray(
    np.zeros([np.shape(depth_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'depth_1', 'lon_1'), coords=[depth_1_mod, lon_1_mod], name='temp_yflux_adv_ym34_1')
for iid, i in enumerate(depth_1_mod):
    for jid, j in enumerate(lon_1_mod):
        temp_yflux_adv_ym34_1_slope_mod[iid, jid], _, _, temp_yflux_adv_ym34_1_p_value_mod[iid, jid], temp_yflux_adv_ym34_1_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_yflux_adv_ym34_1_trans_mod[:, iid, jid])
    print('depth_1_mod ' + str(np.array(i)))
print(temp_yflux_adv_ym34_1_slope_mod)

(14, 35, 30)
depth_1_mod -1.15174989182586
depth_1_mod -3.6486741197120196
depth_1_mod -6.564918471676153
depth_1_mod -9.970869194872916
depth_1_mod -13.948708373749158
depth_1_mod -18.594379460593196
depth_1_mod -24.019873617545198
depth_1_mod -30.355885242559452
depth_1_mod -37.754889932903495
depth_1_mod -46.39470194845016
depth_1_mod -56.48256969937929
depth_1_mod -68.25986482598941
depth_1_mod -82.00740970018322
depth_1_mod -98.05146439730592
depth_1_mod -116.77034928747688
depth_1_mod -138.60160118643546
depth_1_mod -164.04943216631892
depth_1_mod -193.69205664349184
depth_1_mod -228.1881444592732
depth_1_mod -268.2812141854562
depth_1_mod -314.800181990729
depth_1_mod -368.65354740782504
depth_1_mod -430.8139438640983
depth_1_mod -502.28929308570173
depth_1_mod -584.0771003035616
depth_1_mod -677.1002526914099
depth_1_mod -782.1267221440287
depth_1_mod -899.6817765561261
depth_1_mod -1029.9681126743835
depth_1_mod -1172.813371535859
depth_1_mod -1327.6620295174746
depth_1_mod -1

In [8]:
%%time
latL = -34
ekey='025deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_yflux_adv_ym34_025_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='temp_yflux_adv').\
interp(yu_ocean=latL).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=slice(0,2100))
print(temp_yflux_adv_ym34_025_mod_month)

temp_yflux_adv_ym34_025_mod_month.load()
print(temp_yflux_adv_ym34_025_mod_month)

xt_ocean = temp_yflux_adv_ym34_025_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_yflux_adv_ym34_025_mod_month = temp_yflux_adv_ym34_025_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
st_ocean = temp_yflux_adv_ym34_025_mod_month.st_ocean
st_ocean_corrected = -st_ocean
temp_yflux_adv_ym34_025_mod_month = temp_yflux_adv_ym34_025_mod_month.assign_coords(st_ocean=st_ocean_corrected)
print(temp_yflux_adv_ym34_025_mod_month)

temp_yflux_adv_ym34_025_mod = temp_yflux_adv_ym34_025_mod_month.groupby('time.year').mean('time')
print(temp_yflux_adv_ym34_025_mod)

temp_yflux_adv_ym34_025_mod = temp_yflux_adv_ym34_025_mod.sel(year=slice(2004+60*4,2017+60*4))
print(temp_yflux_adv_ym34_025_mod)

025deg_jra55v13_iaf_gmredi6


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'temp_yflux_adv' (time: 300, st_ocean: 35, xt_ocean: 120)>
dask.array<getitem, shape=(300, 35, 120), dtype=float32, chunksize=(1, 10, 92), chunktype=numpy.ndarray>
Coordinates:
  * st_ocean  (st_ocean) float64 1.152 3.649 6.565 ... 1.854e+03 2.046e+03
  * xt_ocean  (xt_ocean) float64 -214.9 -214.6 -214.4 ... -185.6 -185.4 -185.1
  * time      (time) object 1958-06-30 12:00:00 ... 2257-06-30 12:00:00
    yu_ocean  int64 -34
Attributes:
    long_name:      cp*rho*dzt*dxt*v*temp
    units:          Watts
    valid_range:    [-1.e+18  1.e+18]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_t geolat_c
<xarray.DataArray 'temp_yflux_adv' (time: 300, st_ocean: 35, xt_ocean: 120)>
array([[[            nan,             nan,             nan, ...,
         -3.45073300e+11, -2.91015884e+11, -2.01776706e+11],
        [            nan,             nan,             nan, ...,
         -3.90513299e+11, -3.27450256e+11, -2.2

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'temp_yflux_adv' (year: 300, st_ocean: 35, xt_ocean: 120)>
array([[[            nan,             nan,             nan, ...,
         -3.45073300e+11, -2.91015884e+11, -2.01776706e+11],
        [            nan,             nan,             nan, ...,
         -3.90513299e+11, -3.27450256e+11, -2.23287302e+11],
        [            nan,             nan,             nan, ...,
         -4.45875630e+11, -3.72950117e+11, -2.52043251e+11],
        ...,
        [            nan,             nan,             nan, ...,
         -2.98590490e+11, -2.13009346e+10,  2.18815260e+11],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan]],

       [[            nan,             nan,             nan, ...,
         -3.24191217e+11, -1.92962626e+11, -8.10083416e+10],
        [            nan, 

In [ ]:
year = temp_yflux_adv_ym34_025_mod.year
depth_025_mod = temp_yflux_adv_ym34_025_mod.st_ocean
lon_025_mod = temp_yflux_adv_ym34_025_mod.xt_ocean

temp_yflux_adv_ym34_025_trans_mod = temp_yflux_adv_ym34_025_mod
print(np.shape(temp_yflux_adv_ym34_025_trans_mod))
temp_yflux_adv_ym34_025_slope_mod = xr.DataArray(
    np.zeros([np.shape(depth_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'depth_025', 'lon_025'), coords=[depth_025_mod, lon_025_mod], name='temp_yflux_adv_ym34_025')
temp_yflux_adv_ym34_025_p_value_mod = xr.DataArray(
    np.zeros([np.shape(depth_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'depth_025', 'lon_025'), coords=[depth_025_mod, lon_025_mod], name='temp_yflux_adv_ym34_025')
temp_yflux_adv_ym34_025_std_err_mod = xr.DataArray(
    np.zeros([np.shape(depth_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'depth_025', 'lon_025'), coords=[depth_025_mod, lon_025_mod], name='temp_yflux_adv_ym34_025')
for iid, i in enumerate(depth_025_mod):
    for jid, j in enumerate(lon_025_mod):
        temp_yflux_adv_ym34_025_slope_mod[iid, jid], _, _, temp_yflux_adv_ym34_025_p_value_mod[iid, jid], temp_yflux_adv_ym34_025_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_yflux_adv_ym34_025_trans_mod[:, iid, jid])
    print('depth_025_mod ' + str(np.array(i)))
print(temp_yflux_adv_ym34_025_slope_mod)

(14, 35, 120)
depth_025_mod -1.15174989182586
depth_025_mod -3.6486741197120196
depth_025_mod -6.564918471676153
depth_025_mod -9.970869194872916
depth_025_mod -13.948708373749158
depth_025_mod -18.594379460593196
depth_025_mod -24.019873617545198
depth_025_mod -30.355885242559452
depth_025_mod -37.754889932903495
depth_025_mod -46.39470194845016


In [9]:
%%time
latL = -34
ekey='01deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_yflux_adv_ym34_01_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='temp_yflux_adv').\
sel(yu_ocean=latL, method='nearest').\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=slice(0,2100))
print(temp_yflux_adv_ym34_01_mod_month)

temp_yflux_adv_ym34_01_mod_month.load()
print(temp_yflux_adv_ym34_01_mod_month)

xt_ocean = temp_yflux_adv_ym34_01_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_yflux_adv_ym34_01_mod_month = temp_yflux_adv_ym34_01_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
st_ocean = temp_yflux_adv_ym34_01_mod_month.st_ocean
st_ocean_corrected = -st_ocean
temp_yflux_adv_ym34_01_mod_month = temp_yflux_adv_ym34_01_mod_month.assign_coords(st_ocean=st_ocean_corrected)
print(temp_yflux_adv_ym34_01_mod_month)

temp_yflux_adv_ym34_01_mod = temp_yflux_adv_ym34_01_mod_month.groupby('time.year').mean('time')
print(temp_yflux_adv_ym34_01_mod)

temp_yflux_adv_ym34_01_mod = temp_yflux_adv_ym34_01_mod.sel(year=slice(2004,2017))
print(temp_yflux_adv_ym34_01_mod)

01deg_jra55v13_iaf


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'v' (time: 396, st_ocean: 55, xu_ocean: 300)>
dask.array<getitem, shape=(396, 55, 300), dtype=float32, chunksize=(1, 7, 151), chunktype=numpy.ndarray>
Coordinates:
    yu_ocean  float64 -34.01
  * xu_ocean  (xu_ocean) float64 -215.0 -214.9 -214.8 ... -185.3 -185.2 -185.1
  * st_ocean  (st_ocean) float64 0.5413 1.681 2.94 ... 1.858e+03 2.007e+03
  * time      (time) object 1985-01-14 12:00:00 ... 2017-12-14 12:00:00
Attributes:
    long_name:      j-current
    units:          m/sec
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  sea_water_y_velocity
<xarray.DataArray 'v' (time: 396, st_ocean: 55, xu_ocean: 300)>
array([[[        nan,         nan,         nan, ...,  0.0516462 ,
          0.04351566,  0.03024201],
        [        nan,         nan,         nan, ...,  0.0494876 ,
          0.041315  ,  0.02794653],
        [        nan,         na

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [10]:
year = temp_yflux_adv_ym34_01_mod.year
depth_01_mod = temp_yflux_adv_ym34_01_mod.st_ocean
lon_01_mod = temp_yflux_adv_ym34_01_mod.xt_ocean

temp_yflux_adv_ym34_01_trans_mod = temp_yflux_adv_ym34_01_mod
print(np.shape(temp_yflux_adv_ym34_01_trans_mod))
temp_yflux_adv_ym34_01_slope_mod = xr.DataArray(
    np.zeros([np.shape(depth_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'depth_01', 'lon_01'), coords=[depth_01_mod, lon_01_mod], name='temp_yflux_adv_ym34_01')
temp_yflux_adv_ym34_01_p_value_mod = xr.DataArray(
    np.zeros([np.shape(depth_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'depth_01', 'lon_01'), coords=[depth_01_mod, lon_01_mod], name='temp_yflux_adv_ym34_01')
temp_yflux_adv_ym34_01_std_err_mod = xr.DataArray(
    np.zeros([np.shape(depth_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'depth_01', 'lon_01'), coords=[depth_01_mod, lon_01_mod], name='temp_yflux_adv_ym34_01')
for iid, i in enumerate(depth_01_mod):
    for jid, j in enumerate(lon_01_mod):
        temp_yflux_adv_ym34_01_slope_mod[iid, jid], _, _, temp_yflux_adv_ym34_01_p_value_mod[iid, jid], temp_yflux_adv_ym34_01_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_yflux_adv_ym34_01_trans_mod[:, iid, jid])
    print('depth_01_mod ' + str(np.array(i)))
print(temp_yflux_adv_ym34_01_slope_mod)

(14, 55, 300)
depth_01_mod -0.5412807653916101
depth_01_mod -1.680734679831433
depth_01_mod -2.939952648914465
depth_01_mod -4.331521485149508
depth_01_mod -5.8693504240540255
depth_01_mod -7.5688099200502155
depth_01_mod -9.446884959648713
depth_01_mod -11.522344392803275
depth_01_mod -13.815927932333222
depth_01_mod -16.350552632935347
depth_01_mod -19.151540835805992
depth_01_mod -22.24687175218868
depth_01_mod -25.667459058670023
depth_01_mod -29.447457087455206
depth_01_mod -33.62459841385048
depth_01_mod -38.24056586677453
depth_01_mod -43.341402211041604
depth_01_mod -48.97796096317406
depth_01_mod -55.20640199365842
depth_01_mod -62.088735720175855
depth_01_mod -69.69341978534455
depth_01_mod -78.09601210263148
depth_01_mod -87.37988400213499
depth_01_mod -97.63699685168024
depth_01_mod -108.96874488209758
depth_01_mod -121.48686590184016
depth_01_mod -135.31441999260392
depth_01_mod -150.5868339523135
depth_01_mod -167.45300594349283
depth_01_mod -186.07646019149857
depth_01_m

In [11]:
temp_yflux_adv_ym34_1_mod_xr = xr.DataArray(temp_yflux_adv_ym34_1_mod.transpose('st_ocean', 'xt_ocean', 'year'), name='temp_yflux_adv_ym34_1_mod',
                        coords=[depth_1_mod, lon_1_mod, year], 
                        dims=['st_ocean', 'xt_ocean', 'year'])
print(temp_yflux_adv_ym34_1_mod_xr)
temp_yflux_adv_ym34_1_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_1_mod.nc')

temp_yflux_adv_ym34_1_slope_mod_xr = xr.DataArray(temp_yflux_adv_ym34_1_slope_mod, name='temp_yflux_adv_ym34_1_slope_mod',
                        coords=[depth_1_mod, lon_1_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_1_slope_mod_xr)
temp_yflux_adv_ym34_1_slope_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_1_slope_mod.nc')

temp_yflux_adv_ym34_1_p_value_mod_xr = xr.DataArray(temp_yflux_adv_ym34_1_p_value_mod, name='temp_yflux_adv_ym34_1_p_value_mod',
                        coords=[depth_1_mod, lon_1_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_1_p_value_mod_xr)
temp_yflux_adv_ym34_1_p_value_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_1_p_value_mod.nc')

temp_yflux_adv_ym34_1_std_err_mod_xr = xr.DataArray(temp_yflux_adv_ym34_1_std_err_mod, name='temp_yflux_adv_ym34_1_std_err_mod',
                        coords=[depth_1_mod, lon_1_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_1_std_err_mod_xr)
temp_yflux_adv_ym34_1_std_err_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_1_std_err_mod.nc')



temp_yflux_adv_ym34_025_mod_xr = xr.DataArray(temp_yflux_adv_ym34_025_mod.transpose('st_ocean', 'xt_ocean', 'year'), name='temp_yflux_adv_ym34_025_mod',
                        coords=[depth_025_mod, lon_025_mod, year], 
                        dims=['st_ocean', 'xt_ocean', 'year'])
print(temp_yflux_adv_ym34_025_mod_xr)
temp_yflux_adv_ym34_025_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_025_mod.nc')

temp_yflux_adv_ym34_025_slope_mod_xr = xr.DataArray(temp_yflux_adv_ym34_025_slope_mod, name='temp_yflux_adv_ym34_025_slope_mod',
                        coords=[depth_025_mod, lon_025_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_025_slope_mod_xr)
temp_yflux_adv_ym34_025_slope_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_025_slope_mod.nc')

temp_yflux_adv_ym34_025_p_value_mod_xr = xr.DataArray(temp_yflux_adv_ym34_025_p_value_mod, name='temp_yflux_adv_ym34_025_p_value_mod',
                        coords=[depth_025_mod, lon_025_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_025_p_value_mod_xr)
temp_yflux_adv_ym34_025_p_value_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_025_p_value_mod.nc')

temp_yflux_adv_ym34_025_std_err_mod_xr = xr.DataArray(temp_yflux_adv_ym34_025_std_err_mod, name='temp_yflux_adv_ym34_025_std_err_mod',
                        coords=[depth_025_mod, lon_025_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_025_std_err_mod_xr)
temp_yflux_adv_ym34_025_std_err_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_025_std_err_mod.nc')



temp_yflux_adv_ym34_01_mod_xr = xr.DataArray(temp_yflux_adv_ym34_01_mod.transpose('st_ocean', 'xt_ocean', 'year'), name='temp_yflux_adv_ym34_01_mod',
                        coords=[depth_01_mod, lon_01_mod, year], 
                        dims=['st_ocean', 'xt_ocean', 'year'])
print(temp_yflux_adv_ym34_01_mod_xr)
temp_yflux_adv_ym34_01_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_01_mod.nc')

temp_yflux_adv_ym34_01_slope_mod_xr = xr.DataArray(temp_yflux_adv_ym34_01_slope_mod, name='temp_yflux_adv_ym34_01_slope_mod',
                        coords=[depth_01_mod, lon_01_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_01_slope_mod_xr)
temp_yflux_adv_ym34_01_slope_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_01_slope_mod.nc')

temp_yflux_adv_ym34_01_p_value_mod_xr = xr.DataArray(temp_yflux_adv_ym34_01_p_value_mod, name='temp_yflux_adv_ym34_01_p_value_mod',
                        coords=[depth_01_mod, lon_01_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_01_p_value_mod_xr)
temp_yflux_adv_ym34_01_p_value_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_01_p_value_mod.nc')

temp_yflux_adv_ym34_01_std_err_mod_xr = xr.DataArray(temp_yflux_adv_ym34_01_std_err_mod, name='temp_yflux_adv_ym34_01_std_err_mod',
                        coords=[depth_01_mod, lon_01_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym34_01_std_err_mod_xr)
temp_yflux_adv_ym34_01_std_err_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym34_01_std_err_mod.nc')

<xarray.DataArray 'v_ym34_1_mod' (st_ocean: 35, xu_ocean: 31, year: 14)>
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [-0.03642803, -0.05535694, -0.04368769, ..., -0.05250392,
         -0.05890884, -0.05270528]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         

<xarray.DataArray 'v_ym34_025_slope_mod' (st_ocean: 35, xu_ocean: 121)>
array([[        nan,         nan,         nan, ...,  0.00186184,
         0.0012931 ,  0.00120846],
       [        nan,         nan,         nan, ...,  0.00188366,
         0.00131379,  0.00122844],
       [        nan,         nan,         nan, ...,  0.00190427,
         0.001332  ,  0.00124307],
       ...,
       [        nan,         nan,         nan, ...,  0.00011505,
        -0.00017808,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])
Coordinates:
  * st_ocean  (st_ocean) float64 -1.152 -3.649 -6.565 ... -1.854e+03 -2.046e+03
  * xu_ocean  (xu_ocean) float64 145.0 145.2 145.5 145.8 ... 174.5 174.8 175.0
<xarray.DataArray 'v_ym34_025_p_value_mod' (st_ocean: 35, xu_ocean: 121)>
array([[       nan,        nan,        nan, ..., 0.30494972, 0.354844

In [12]:
%%time
latL = -42
ekey='1deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_yflux_adv_ym42_1_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='v').\
interp(yu_ocean=latL).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=slice(0,2100))
print(temp_yflux_adv_ym42_1_mod_month)

temp_yflux_adv_ym42_1_mod_month.load()
print(temp_yflux_adv_ym42_1_mod_month)

xt_ocean = temp_yflux_adv_ym42_1_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_yflux_adv_ym42_1_mod_month = temp_yflux_adv_ym42_1_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
st_ocean = temp_yflux_adv_ym42_1_mod_month.st_ocean
st_ocean_corrected = -st_ocean
temp_yflux_adv_ym42_1_mod_month = temp_yflux_adv_ym42_1_mod_month.assign_coords(st_ocean=st_ocean_corrected)
print(temp_yflux_adv_ym42_1_mod_month)

temp_yflux_adv_ym42_1_mod = temp_yflux_adv_ym42_1_mod_month.groupby('time.year').mean('time')
print(temp_yflux_adv_ym42_1_mod)

temp_yflux_adv_ym42_1_mod = temp_yflux_adv_ym42_1_mod.sel(year=slice(2004+60*4,2017+60*4))
print(temp_yflux_adv_ym42_1_mod)


ekey='025deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_yflux_adv_ym42_025_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='v').\
interp(yu_ocean=latL).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=slice(0,2100))
print(temp_yflux_adv_ym42_025_mod_month)

temp_yflux_adv_ym42_025_mod_month.load()
print(temp_yflux_adv_ym42_025_mod_month)

xt_ocean = temp_yflux_adv_ym42_025_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_yflux_adv_ym42_025_mod_month = temp_yflux_adv_ym42_025_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
st_ocean = temp_yflux_adv_ym42_025_mod_month.st_ocean
st_ocean_corrected = -st_ocean
temp_yflux_adv_ym42_025_mod_month = temp_yflux_adv_ym42_025_mod_month.assign_coords(st_ocean=st_ocean_corrected)
print(temp_yflux_adv_ym42_025_mod_month)

temp_yflux_adv_ym42_025_mod = temp_yflux_adv_ym42_025_mod_month.groupby('time.year').mean('time')
print(temp_yflux_adv_ym42_025_mod)

temp_yflux_adv_ym42_025_mod = temp_yflux_adv_ym42_025_mod.sel(year=slice(2004+60*4,2017+60*4))
print(temp_yflux_adv_ym42_025_mod)


ekey='01deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_yflux_adv_ym42_01_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='v').\
sel(yu_ocean=latL, method='nearest').\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=slice(0,2100))
print(temp_yflux_adv_ym42_01_mod_month)

temp_yflux_adv_ym42_01_mod_month.load()
print(temp_yflux_adv_ym42_01_mod_month)

xt_ocean = temp_yflux_adv_ym42_01_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_yflux_adv_ym42_01_mod_month = temp_yflux_adv_ym42_01_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
st_ocean = temp_yflux_adv_ym42_01_mod_month.st_ocean
st_ocean_corrected = -st_ocean
temp_yflux_adv_ym42_01_mod_month = temp_yflux_adv_ym42_01_mod_month.assign_coords(st_ocean=st_ocean_corrected)
print(temp_yflux_adv_ym42_01_mod_month)

temp_yflux_adv_ym42_01_mod = temp_yflux_adv_ym42_01_mod_month.groupby('time.year').mean('time')
print(temp_yflux_adv_ym42_01_mod)

temp_yflux_adv_ym42_01_mod = temp_yflux_adv_ym42_01_mod.sel(year=slice(2004,2017))
print(temp_yflux_adv_ym42_01_mod)


year = temp_yflux_adv_ym42_1_mod.year
depth_1_mod = temp_yflux_adv_ym42_1_mod.st_ocean
lon_1_mod = temp_yflux_adv_ym42_1_mod.xt_ocean
temp_yflux_adv_ym42_1_trans_mod = temp_yflux_adv_ym42_1_mod
print(np.shape(temp_yflux_adv_ym42_1_trans_mod))
temp_yflux_adv_ym42_1_slope_mod = xr.DataArray(
    np.zeros([np.shape(depth_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'depth_1', 'lon_1'), coords=[depth_1_mod, lon_1_mod], name='temp_yflux_adv_ym42_1')
temp_yflux_adv_ym42_1_p_value_mod = xr.DataArray(
    np.zeros([np.shape(depth_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'depth_1', 'lon_1'), coords=[depth_1_mod, lon_1_mod], name='temp_yflux_adv_ym42_1')
temp_yflux_adv_ym42_1_std_err_mod = xr.DataArray(
    np.zeros([np.shape(depth_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'depth_1', 'lon_1'), coords=[depth_1_mod, lon_1_mod], name='temp_yflux_adv_ym42_1')
for iid, i in enumerate(depth_1_mod):
    for jid, j in enumerate(lon_1_mod):
        temp_yflux_adv_ym42_1_slope_mod[iid, jid], _, _, temp_yflux_adv_ym42_1_p_value_mod[iid, jid], temp_yflux_adv_ym42_1_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_yflux_adv_ym42_1_trans_mod[:, iid, jid])
    print('depth_1_mod ' + str(np.array(i)))
print(temp_yflux_adv_ym42_1_slope_mod)
year = temp_yflux_adv_ym42_025_mod.year
depth_025_mod = temp_yflux_adv_ym42_025_mod.st_ocean
lon_025_mod = temp_yflux_adv_ym42_025_mod.xt_ocean
temp_yflux_adv_ym42_025_trans_mod = temp_yflux_adv_ym42_025_mod
print(np.shape(temp_yflux_adv_ym42_025_trans_mod))
temp_yflux_adv_ym42_025_slope_mod = xr.DataArray(
    np.zeros([np.shape(depth_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'depth_025', 'lon_025'), coords=[depth_025_mod, lon_025_mod], name='temp_yflux_adv_ym42_025')
temp_yflux_adv_ym42_025_p_value_mod = xr.DataArray(
    np.zeros([np.shape(depth_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'depth_025', 'lon_025'), coords=[depth_025_mod, lon_025_mod], name='temp_yflux_adv_ym42_025')
temp_yflux_adv_ym42_025_std_err_mod = xr.DataArray(
    np.zeros([np.shape(depth_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'depth_025', 'lon_025'), coords=[depth_025_mod, lon_025_mod], name='temp_yflux_adv_ym42_025')
for iid, i in enumerate(depth_025_mod):
    for jid, j in enumerate(lon_025_mod):
        temp_yflux_adv_ym42_025_slope_mod[iid, jid], _, _, temp_yflux_adv_ym42_025_p_value_mod[iid, jid], temp_yflux_adv_ym42_025_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_yflux_adv_ym42_025_trans_mod[:, iid, jid])
    print('depth_025_mod ' + str(np.array(i)))
print(temp_yflux_adv_ym42_025_slope_mod)
year = temp_yflux_adv_ym42_01_mod.year
depth_01_mod = temp_yflux_adv_ym42_01_mod.st_ocean
lon_01_mod = temp_yflux_adv_ym42_01_mod.xt_ocean
temp_yflux_adv_ym42_01_trans_mod = temp_yflux_adv_ym42_01_mod
print(np.shape(temp_yflux_adv_ym42_01_trans_mod))
temp_yflux_adv_ym42_01_slope_mod = xr.DataArray(
    np.zeros([np.shape(depth_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'depth_01', 'lon_01'), coords=[depth_01_mod, lon_01_mod], name='temp_yflux_adv_ym42_01')
temp_yflux_adv_ym42_01_p_value_mod = xr.DataArray(
    np.zeros([np.shape(depth_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'depth_01', 'lon_01'), coords=[depth_01_mod, lon_01_mod], name='temp_yflux_adv_ym42_01')
temp_yflux_adv_ym42_01_std_err_mod = xr.DataArray(
    np.zeros([np.shape(depth_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'depth_01', 'lon_01'), coords=[depth_01_mod, lon_01_mod], name='temp_yflux_adv_ym42_01')
for iid, i in enumerate(depth_01_mod):
    for jid, j in enumerate(lon_01_mod):
        temp_yflux_adv_ym42_01_slope_mod[iid, jid], _, _, temp_yflux_adv_ym42_01_p_value_mod[iid, jid], temp_yflux_adv_ym42_01_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_yflux_adv_ym42_01_trans_mod[:, iid, jid])
    print('depth_01_mod ' + str(np.array(i)))
print(temp_yflux_adv_ym42_01_slope_mod)

1deg_jra55v13_iaf_spinup1_B1


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'v' (time: 300, st_ocean: 35, xu_ocean: 31)>
dask.array<getitem, shape=(300, 35, 31), dtype=float32, chunksize=(1, 25, 31), chunktype=numpy.ndarray>
Coordinates:
  * xu_ocean  (xu_ocean) float64 -215.0 -214.0 -213.0 ... -187.0 -186.0 -185.0
  * st_ocean  (st_ocean) float64 1.152 3.649 6.565 ... 1.854e+03 2.046e+03
  * time      (time) object 1958-07-02 12:00:00 ... 2257-07-02 12:00:00
    yu_ocean  int64 -42
Attributes:
    long_name:      j-current
    units:          m/sec
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  sea_water_y_velocity
<xarray.DataArray 'v' (time: 300, st_ocean: 35, xu_ocean: 31)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
      

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
befo

<xarray.DataArray 'v' (time: 300, st_ocean: 35, xu_ocean: 121)>
dask.array<getitem, shape=(300, 35, 121), dtype=float32, chunksize=(1, 10, 92), chunktype=numpy.ndarray>
Coordinates:
  * xu_ocean  (xu_ocean) float64 -215.0 -214.8 -214.5 ... -185.5 -185.2 -185.0
  * st_ocean  (st_ocean) float64 1.152 3.649 6.565 ... 1.854e+03 2.046e+03
  * time      (time) object 1958-06-30 12:00:00 ... 2257-06-30 12:00:00
    yu_ocean  int64 -42
Attributes:
    long_name:      j-current
    units:          m/sec
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  sea_water_y_velocity
<xarray.DataArray 'v' (time: 300, st_ocean: 35, xu_ocean: 121)>
array([[[-0.0004123 ,         nan,         nan, ..., -0.01272566,
         -0.01049572, -0.04422767],
        [-0.00180471,         nan,         nan, ..., -0.00626995,
         -0.00279138, -0.03661795],
        [-0.00348124,         nan,   

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
befo

<xarray.DataArray 'v' (time: 396, st_ocean: 55, xu_ocean: 300)>
dask.array<getitem, shape=(396, 55, 300), dtype=float32, chunksize=(1, 7, 151), chunktype=numpy.ndarray>
Coordinates:
    yu_ocean  float64 -42.03
  * xu_ocean  (xu_ocean) float64 -215.0 -214.9 -214.8 ... -185.3 -185.2 -185.1
  * st_ocean  (st_ocean) float64 0.5413 1.681 2.94 ... 1.858e+03 2.007e+03
  * time      (time) object 1985-01-14 12:00:00 ... 2017-12-14 12:00:00
Attributes:
    long_name:      j-current
    units:          m/sec
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  sea_water_y_velocity
<xarray.DataArray 'v' (time: 396, st_ocean: 55, xu_ocean: 300)>
array([[[ 0.02931969,  0.04194338,         nan, ..., -0.25318325,
         -0.18784206, -0.09340503],
        [ 0.02202233,  0.03438191,         nan, ..., -0.23497023,
         -0.16927943, -0.07443643],
        [ 0.01652396,  0.0275988

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


depth_1_mod -1.15174989182586
depth_1_mod -3.6486741197120196
depth_1_mod -6.564918471676153
depth_1_mod -9.970869194872916
depth_1_mod -13.948708373749158
depth_1_mod -18.594379460593196
depth_1_mod -24.019873617545198
depth_1_mod -30.355885242559452
depth_1_mod -37.754889932903495
depth_1_mod -46.39470194845016
depth_1_mod -56.48256969937929
depth_1_mod -68.25986482598941
depth_1_mod -82.00740970018322
depth_1_mod -98.05146439730592
depth_1_mod -116.77034928747688
depth_1_mod -138.60160118643546
depth_1_mod -164.04943216631892
depth_1_mod -193.69205664349184
depth_1_mod -228.1881444592732
depth_1_mod -268.2812141854562
depth_1_mod -314.800181990729
depth_1_mod -368.65354740782504
depth_1_mod -430.8139438640983
depth_1_mod -502.28929308570173
depth_1_mod -584.0771003035616
depth_1_mod -677.1002526914099
depth_1_mod -782.1267221440287
depth_1_mod -899.6817765561261
depth_1_mod -1029.9681126743835
depth_1_mod -1172.813371535859
depth_1_mod -1327.6620295174746
depth_1_mod -1493.618454761

In [13]:
temp_yflux_adv_ym42_1_mod_xr = xr.DataArray(temp_yflux_adv_ym42_1_mod.transpose('st_ocean', 'xt_ocean', 'year'), name='temp_yflux_adv_ym42_1_mod',
                        coords=[depth_1_mod, lon_1_mod, year], 
                        dims=['st_ocean', 'xt_ocean', 'year'])
print(temp_yflux_adv_ym42_1_mod_xr)
temp_yflux_adv_ym42_1_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_1_mod.nc')

temp_yflux_adv_ym42_1_slope_mod_xr = xr.DataArray(temp_yflux_adv_ym42_1_slope_mod, name='temp_yflux_adv_ym42_1_slope_mod',
                        coords=[depth_1_mod, lon_1_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_1_slope_mod_xr)
temp_yflux_adv_ym42_1_slope_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_1_slope_mod.nc')

temp_yflux_adv_ym42_1_p_value_mod_xr = xr.DataArray(temp_yflux_adv_ym42_1_p_value_mod, name='temp_yflux_adv_ym42_1_p_value_mod',
                        coords=[depth_1_mod, lon_1_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_1_p_value_mod_xr)
temp_yflux_adv_ym42_1_p_value_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_1_p_value_mod.nc')

temp_yflux_adv_ym42_1_std_err_mod_xr = xr.DataArray(temp_yflux_adv_ym42_1_std_err_mod, name='temp_yflux_adv_ym42_1_std_err_mod',
                        coords=[depth_1_mod, lon_1_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_1_std_err_mod_xr)
temp_yflux_adv_ym42_1_std_err_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_1_std_err_mod.nc')



temp_yflux_adv_ym42_025_mod_xr = xr.DataArray(temp_yflux_adv_ym42_025_mod.transpose('st_ocean', 'xt_ocean', 'year'), name='temp_yflux_adv_ym42_025_mod',
                        coords=[depth_025_mod, lon_025_mod, year], 
                        dims=['st_ocean', 'xt_ocean', 'year'])
print(temp_yflux_adv_ym42_025_mod_xr)
temp_yflux_adv_ym42_025_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_025_mod.nc')

temp_yflux_adv_ym42_025_slope_mod_xr = xr.DataArray(temp_yflux_adv_ym42_025_slope_mod, name='temp_yflux_adv_ym42_025_slope_mod',
                        coords=[depth_025_mod, lon_025_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_025_slope_mod_xr)
temp_yflux_adv_ym42_025_slope_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_025_slope_mod.nc')

temp_yflux_adv_ym42_025_p_value_mod_xr = xr.DataArray(temp_yflux_adv_ym42_025_p_value_mod, name='temp_yflux_adv_ym42_025_p_value_mod',
                        coords=[depth_025_mod, lon_025_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_025_p_value_mod_xr)
temp_yflux_adv_ym42_025_p_value_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_025_p_value_mod.nc')

temp_yflux_adv_ym42_025_std_err_mod_xr = xr.DataArray(temp_yflux_adv_ym42_025_std_err_mod, name='temp_yflux_adv_ym42_025_std_err_mod',
                        coords=[depth_025_mod, lon_025_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_025_std_err_mod_xr)
temp_yflux_adv_ym42_025_std_err_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_025_std_err_mod.nc')



temp_yflux_adv_ym42_01_mod_xr = xr.DataArray(temp_yflux_adv_ym42_01_mod.transpose('st_ocean', 'xt_ocean', 'year'), name='temp_yflux_adv_ym42_01_mod',
                        coords=[depth_01_mod, lon_01_mod, year], 
                        dims=['st_ocean', 'xt_ocean', 'year'])
print(temp_yflux_adv_ym42_01_mod_xr)
temp_yflux_adv_ym42_01_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_01_mod.nc')

temp_yflux_adv_ym42_01_slope_mod_xr = xr.DataArray(temp_yflux_adv_ym42_01_slope_mod, name='temp_yflux_adv_ym42_01_slope_mod',
                        coords=[depth_01_mod, lon_01_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_01_slope_mod_xr)
temp_yflux_adv_ym42_01_slope_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_01_slope_mod.nc')

temp_yflux_adv_ym42_01_p_value_mod_xr = xr.DataArray(temp_yflux_adv_ym42_01_p_value_mod, name='temp_yflux_adv_ym42_01_p_value_mod',
                        coords=[depth_01_mod, lon_01_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_01_p_value_mod_xr)
temp_yflux_adv_ym42_01_p_value_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_01_p_value_mod.nc')

temp_yflux_adv_ym42_01_std_err_mod_xr = xr.DataArray(temp_yflux_adv_ym42_01_std_err_mod, name='temp_yflux_adv_ym42_01_std_err_mod',
                        coords=[depth_01_mod, lon_01_mod], 
                        dims=['st_ocean', 'xt_ocean'])
print(temp_yflux_adv_ym42_01_std_err_mod_xr)
temp_yflux_adv_ym42_01_std_err_mod_xr.to_netcdf(output_path + 'temp_yflux_adv_ym42_01_std_err_mod.nc')

<xarray.DataArray 'v_ym42_1_mod' (st_ocean: 35, xu_ocean: 31, year: 14)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       ...,

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, 

<xarray.DataArray 'v_ym42_025_p_value_mod' (st_ocean: 35, xu_ocean: 121)>
array([[0.82683905,        nan,        nan, ..., 0.98046774, 0.12631837,
        0.7122319 ],
       [0.79303097,        nan,        nan, ..., 0.86078825, 0.14319229,
        0.5689869 ],
       [0.74530427,        nan,        nan, ..., 0.76480245, 0.16249893,
        0.47815038],
       ...,
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan]])
Coordinates:
  * st_ocean  (st_ocean) float64 -1.152 -3.649 -6.565 ... -1.854e+03 -2.046e+03
  * xu_ocean  (xu_ocean) float64 145.0 145.2 145.5 145.8 ... 174.5 174.8 175.0
<xarray.DataArray 'v_ym42_025_std_err_mod' (st_ocean: 35, xu_ocean: 121)>
array([[0.00040257,        nan,        nan, ..., 0.00075318, 0.00057574,
        0.00063751],
       [0