In [1]:
'''
This file plots CMIP5 RCP - HIST over South Australia
/Users/earl/Desktop/Yang
and places the outputs in
/Users/earl/Dropbox/CMIP5/figures

Earl Duran 
created: 19-Mar-18
e.duran@unsw.edu.au
'''

import cosima_cookbook as cc
import os
import xarray as xr
import numpy as np
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import matplotlib
import sys
import pickle
import itertools
def find_nearest_index(array, value):
    return int((np.abs(array - value)).argmin())
from scipy import interpolate
from scipy import stats
from dask.distributed import Client

import cartopy.crs as ccrs
import cartopy.feature as cft
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
def arange(start,end,stride=1):
    return np.arange(start,end+0.00000001,stride)

import sys, os
sys.path.append(os.path.join(os.getcwd(), '..'))  # so we can import ../exptdata
import exptdata
print('Available exptdata keys: ', [k for k in exptdata.exptdict.keys()])

session = cc.database.create_session()

Available exptdata keys:  ['1deg', '025deg', '01deg']


In [2]:
%%javascript
IPython.notebook.kernel.execute('nb_name = ' + '"' + IPython.notebook.notebook_name + '"')

<IPython.core.display.Javascript object>

In [3]:
client = Client()
client

<Client: 'tcp://127.0.0.1:37393' processes=4 threads=8, memory=33.67 GB>

In [4]:
# input_path = '/g/data/e14/erd561/NOAA_OI_SST_V2/'

output_path = '/g/data/e14/erd561/Australia_3/'

In [5]:
%%time
latS = -80
latN = 20
lonW = 140-360
lonE = 290-360
ekey='1deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

tau_y_z0_1_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='tau_y').\
sel(yu_ocean=arange(latS,latN,1), method='nearest').\
sel(xu_ocean=arange(lonW,lonE,1), method='nearest')
print(tau_y_z0_1_mod_month)

tau_y_z0_1_mod_month.load()
print(tau_y_z0_1_mod_month)

xu_ocean = tau_y_z0_1_mod_month.xu_ocean
xu_ocean_corrected = xu_ocean + 360
tau_y_z0_1_mod_month = tau_y_z0_1_mod_month.assign_coords(xu_ocean=xu_ocean_corrected)
print(tau_y_z0_1_mod_month)

tau_y_z0_1_mod = tau_y_z0_1_mod_month.groupby('time.year').mean('time')
print(tau_y_z0_1_mod)

tau_y_z0_1_mod = tau_y_z0_1_mod.sel(year=slice(1993+60*4,2017+60*4))
print(tau_y_z0_1_mod)

1deg_jra55v13_iaf_spinup1_B1


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'tau_y' (time: 3600, yu_ocean: 101, xu_ocean: 151)>
dask.array<getitem, shape=(3600, 101, 151), dtype=float32, chunksize=(1, 101, 151), chunktype=numpy.ndarray>
Coordinates:
  * xu_ocean  (xu_ocean) float64 -220.0 -219.0 -218.0 ... -72.0 -71.0 -70.0
  * yu_ocean  (yu_ocean) float64 -77.75 -77.75 -77.75 ... 18.22 18.97 19.76
  * time      (time) object 1958-01-16 12:00:00 ... 2257-12-16 12:00:00
Attributes:
    long_name:      j-directed wind stress forcing v-velocity
    units:          N/m^2
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  surface_downward_y_stress
<xarray.DataArray 'tau_y' (time: 3600, yu_ocean: 101, xu_ocean: 151)>
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [ 

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'tau_y' (year: 300, yu_ocean: 101, xu_ocean: 151)>
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [-0.01072051, -0.01167396, -0.01218345, ...,         nan,
                 nan,         nan],
        [-0.0105339 , -0.01062137, -0.01101869, ...,         nan,
                 nan,         nan],
        [-0.01036107, -0.00973678, -0.00923256, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]

In [6]:
year = tau_y_z0_1_mod.year
lat_1_mod = tau_y_z0_1_mod.yu_ocean
lon_1_mod = tau_y_z0_1_mod.xu_ocean

tau_y_z0_1_trans_mod = tau_y_z0_1_mod
print(np.shape(tau_y_z0_1_trans_mod))
tau_y_z0_1_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='tau_y_z0_1')
tau_y_z0_1_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='tau_y_z0_1')
tau_y_z0_1_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='tau_y_z0_1')
for iid, i in enumerate(lat_1_mod):
    for jid, j in enumerate(lon_1_mod):
        tau_y_z0_1_slope_mod[iid, jid], _, _, tau_y_z0_1_p_value_mod[iid, jid], tau_y_z0_1_std_err_mod[iid, jid] = \
        stats.linregress(year, tau_y_z0_1_trans_mod[:, iid, jid])
    print('lat_1_mod ' + str(np.array(i)))
print(tau_y_z0_1_slope_mod)

(25, 101, 151)
lat_1_mod -77.7531683885388
lat_1_mod -77.7531683885388
lat_1_mod -77.7531683885388
lat_1_mod -77.00641259100644
lat_1_mod -75.9729647525201
lat_1_mod -74.86085534808328
lat_1_mod -73.95296132370986
lat_1_mod -72.96570939923888
lat_1_mod -71.885889076368
lat_1_mod -71.10867977935483
lat_1_mod -69.84906491784008
lat_1_mod -68.94283782351798
lat_1_mod -67.98072752895108
lat_1_mod -66.96083978225538
lat_1_mod -65.88166483095814
lat_1_mod -64.74208746915161
lat_1_mod -64.14940914737063
lat_1_mod -62.918017835627595
lat_1_mod -62.27927927724076
lat_1_mod -60.95584415500419
lat_1_mod -60.27127522056853
lat_1_mod -58.85694367835927
lat_1_mod -58.12745998812029
lat_1_mod -56.62473949913835
lat_1_mod -55.85192873260888
lat_1_mod -55.06514135034383
lat_1_mod -54.26464933342449
lat_1_mod -52.623752879356864
lat_1_mod -51.7840044546795
lat_1_mod -50.931862328421644
lat_1_mod -50.067707258186175
lat_1_mod -49.19193999593566
lat_1_mod -48.304980620980295
lat_1_mod -47.40726784079731
l

In [7]:
%%time
ekey='025deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

tau_y_z0_025_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='tau_y').\
sel(yu_ocean=arange(latS,latN,1), method='nearest').\
sel(xu_ocean=arange(lonW,lonE,1), method='nearest')
print(tau_y_z0_025_mod_month)

tau_y_z0_025_mod_month.load()
print(tau_y_z0_025_mod_month)

xu_ocean = tau_y_z0_025_mod_month.xu_ocean
xu_ocean_corrected = xu_ocean + 360
tau_y_z0_025_mod_month = tau_y_z0_025_mod_month.assign_coords(xu_ocean=xu_ocean_corrected)
print(tau_y_z0_025_mod_month)

tau_y_z0_025_mod = tau_y_z0_025_mod_month.groupby('time.year').mean('time')
print(tau_y_z0_025_mod)

tau_y_z0_025_mod = tau_y_z0_025_mod.sel(year=slice(1993+60*4,2017+60*4))
print(tau_y_z0_025_mod)

025deg_jra55v13_iaf_gmredi6


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'tau_y' (time: 3600, yu_ocean: 101, xu_ocean: 151)>
dask.array<getitem, shape=(3600, 101, 151), dtype=float32, chunksize=(1, 91, 121), chunktype=numpy.ndarray>
Coordinates:
  * xu_ocean  (xu_ocean) float64 -220.0 -219.0 -218.0 ... -72.0 -71.0 -70.0
  * yu_ocean  (yu_ocean) float64 -79.97 -79.02 -77.96 ... 17.95 18.9 20.08
  * time      (time) object 1958-01-14 12:00:00 ... 2257-12-14 12:00:00
Attributes:
    long_name:      j-directed wind stress forcing v-velocity
    units:          N/m^2
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  surface_downward_y_stress
<xarray.DataArray 'tau_y' (time: 3600, yu_ocean: 101, xu_ocean: 151)>
array([[[            nan,             nan,             nan, ...,
                     nan,             nan,             nan],
        [            nan,             nan,             nan, ...,
                     nan,

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'tau_y' (year: 300, yu_ocean: 101, xu_ocean: 151)>
array([[[            nan,             nan,             nan, ...,
                     nan,             nan,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan],
        [            nan,             nan,             nan, ...,
                     nan,             nan,             nan],
        ...,
        [-1.10248411e-02, -1.18939364e-02, -1.27288364e-02, ...,
          9.47882328e-03, -1.12410234e-02, -1.67087391e-02],
        [-1.05082775e-02, -1.04955239e-02, -1.13305748e-02, ...,
                     nan,             nan,             nan],
        [-1.02437912e-02, -8.96056369e-03, -8.46842956e-03, ...,
         -9.47354920e-03, -3.87967541e-03, -2.62625632e-04]],

       [[            nan,             nan,             nan, ...,
                     nan,             nan,             nan],
        [            nan,         

In [8]:
lat_025_mod = tau_y_z0_025_mod.yu_ocean
lon_025_mod = tau_y_z0_025_mod.xu_ocean

tau_y_z0_025_trans_mod = tau_y_z0_025_mod
print(np.shape(tau_y_z0_025_trans_mod))
tau_y_z0_025_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='tau_y_z0_025')
tau_y_z0_025_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='tau_y_z0_025')
tau_y_z0_025_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='tau_y_z0_025')
for iid, i in enumerate(lat_025_mod):
    for jid, j in enumerate(lon_025_mod):
        tau_y_z0_025_slope_mod[iid, jid], _, _, tau_y_z0_025_p_value_mod[iid, jid], tau_y_z0_025_std_err_mod[iid, jid] = \
        stats.linregress(year, tau_y_z0_025_trans_mod[:, iid, jid])
    print('lat_025_mod ' + str(np.array(i)))
print(tau_y_z0_025_slope_mod)

(25, 101, 151)
lat_025_mod -79.96821564718513
lat_025_mod -79.01782834434088
lat_025_mod -77.96184245229172
lat_025_mod -77.01145514944747
lat_025_mod -75.9554692573983
lat_025_mod -75.00508195455406
lat_025_mod -73.94909606250489
lat_025_mod -72.99870875966064
lat_025_mod -72.0483214568164
lat_025_mod -70.99233556476723
lat_025_mod -70.04194826192298
lat_025_mod -68.98596236987382
lat_025_mod -68.03557506702957
lat_025_mod -66.9795891749804
lat_025_mod -66.02920187213616
lat_025_mod -64.9731343584332
lat_025_mod -64.00419801547245
lat_025_mod -63.000453214324764
lat_025_mod -61.960968741022334
lat_025_mod -61.00623630265623
lat_025_mod -60.02190673823756
lat_025_mod -59.00736214040289
lat_025_mod -57.96200298543457
lat_025_mod -57.02158171167255
lat_025_mod -56.05675532004928
lat_025_mod -55.06717120897921
lat_025_mod -54.052496893222745
lat_025_mod -53.012422566369025
lat_025_mod -51.94666372937093
lat_025_mod -51.0125182145253
lat_025_mod -50.059170111641855
lat_025_mod -48.92249454

In [9]:
%%time
ekey='01deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

tau_y_z0_01_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean_month.nc',
                                     variable='tau_y').\
sel(yu_ocean=arange(latS,latN,1), method='nearest').\
sel(xu_ocean=arange(lonW,lonE,1), method='nearest')
print(tau_y_z0_01_mod_month)

tau_y_z0_01_mod_month.load()
print(tau_y_z0_01_mod_month)

xu_ocean = tau_y_z0_01_mod_month.xu_ocean
xu_ocean_corrected = xu_ocean + 360
tau_y_z0_01_mod_month = tau_y_z0_01_mod_month.assign_coords(xu_ocean=xu_ocean_corrected)
print(tau_y_z0_01_mod_month)

tau_y_z0_01_mod = tau_y_z0_01_mod_month.groupby('time.year').mean('time')
print(tau_y_z0_01_mod)

tau_y_z0_01_mod = tau_y_z0_01_mod.sel(year=slice(1993,2017))
print(tau_y_z0_01_mod)

01deg_jra55v13_iaf


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'tau_y' (time: 396, yu_ocean: 101, xu_ocean: 151)>
dask.array<getitem, shape=(396, 101, 151), dtype=float32, chunksize=(1, 60, 90), chunktype=numpy.ndarray>
Coordinates:
  * xu_ocean  (xu_ocean) float64 -220.0 -219.0 -218.0 ... -72.0 -71.0 -70.0
  * yu_ocean  (yu_ocean) float64 -79.99 -79.02 -78.0 -76.99 ... 18.0 19.04 19.98
  * time      (time) object 1985-01-14 12:00:00 ... 2017-12-14 12:00:00
Attributes:
    long_name:      j-directed wind stress forcing v-velocity
    units:          N/m^2
    valid_range:    [-10.  10.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    coordinates:    geolon_c geolat_c
    standard_name:  surface_downward_y_stress
<xarray.DataArray 'tau_y' (time: 396, yu_ocean: 101, xu_ocean: 151)>
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [ 

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [10]:
year = tau_y_z0_01_mod.year
lat_01_mod = tau_y_z0_01_mod.yu_ocean
lon_01_mod = tau_y_z0_01_mod.xu_ocean

tau_y_z0_01_trans_mod = tau_y_z0_01_mod
print(np.shape(tau_y_z0_01_trans_mod))
tau_y_z0_01_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'lat_01', 'lon_01'), coords=[lat_01_mod, lon_01_mod], name='tau_y_z0_01')
tau_y_z0_01_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'lat_01', 'lon_01'), coords=[lat_01_mod, lon_01_mod], name='tau_y_z0_01')
tau_y_z0_01_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'lat_01', 'lon_01'), coords=[lat_01_mod, lon_01_mod], name='tau_y_z0_01')
for iid, i in enumerate(lat_01_mod):
    for jid, j in enumerate(lon_01_mod):
        tau_y_z0_01_slope_mod[iid, jid], _, _, tau_y_z0_01_p_value_mod[iid, jid], tau_y_z0_01_std_err_mod[iid, jid] = \
        stats.linregress(year, tau_y_z0_01_trans_mod[:, iid, jid])
    print('lat_01_mod ' + str(np.array(i)))
print(tau_y_z0_01_slope_mod)

(25, 101, 151)
lat_01_mod -79.98928878727199
lat_01_mod -79.01778363652085
lat_01_mod -78.00403913138922
lat_01_mod -76.9902946262576
lat_01_mod -76.01878947550645
lat_01_mod -75.00504497037483
lat_01_mod -73.9913004652432
lat_01_mod -73.01979531449206
lat_01_mod -72.00605080936043
lat_01_mod -70.9923063042288
lat_01_mod -70.02080115347766
lat_01_mod -69.00705664834604
lat_01_mod -67.99331214321441
lat_01_mod -66.97956763808278
lat_01_mod -66.00806248733164
lat_01_mod -64.99430220674928
lat_01_mod -64.0042209455608
lat_01_mod -62.97776694305129
lat_01_mod -62.007960199967066
lat_01_mod -61.00625549764092
lat_01_mod -60.02192466827543
lat_01_mod -59.007378755945275
lat_01_mod -58.01502712478788
lat_01_mod -56.99436964151279
lat_01_mod -56.000890558457534
lat_01_mod -54.98119819398587
lat_01_mod -53.99376127037148
lat_01_mod -52.98233889038113
lat_01_mod -52.008268394713866
lat_01_mod -51.012524640214004
lat_01_mod -49.994932844070924
lat_01_mod -49.02096313942841
lat_01_mod -48.02755332

In [11]:
tau_y_z0_1_mod_xr = xr.DataArray(tau_y_z0_1_mod.transpose('yu_ocean', 'xu_ocean', 'year'), name='tau_y_z0_1_mod',
                        coords=[lat_1_mod, lon_1_mod, year], 
                        dims=['yu_ocean', 'xu_ocean', 'year'])
print(tau_y_z0_1_mod_xr)
tau_y_z0_1_mod_xr.to_netcdf(output_path + 'tau_y_z0_1_mod.nc')

tau_y_z0_1_slope_mod_xr = xr.DataArray(tau_y_z0_1_slope_mod, name='tau_y_z0_1_slope_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_1_slope_mod_xr)
tau_y_z0_1_slope_mod_xr.to_netcdf(output_path + 'tau_y_z0_1_slope_mod.nc')

tau_y_z0_1_p_value_mod_xr = xr.DataArray(tau_y_z0_1_p_value_mod, name='tau_y_z0_1_p_value_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_1_p_value_mod_xr)
tau_y_z0_1_p_value_mod_xr.to_netcdf(output_path + 'tau_y_z0_1_p_value_mod.nc')

tau_y_z0_1_std_err_mod_xr = xr.DataArray(tau_y_z0_1_std_err_mod, name='tau_y_z0_1_std_err_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_1_std_err_mod_xr)
tau_y_z0_1_std_err_mod_xr.to_netcdf(output_path + 'tau_y_z0_1_std_err_mod.nc')



tau_y_z0_025_mod_xr = xr.DataArray(tau_y_z0_025_mod.transpose('yu_ocean', 'xu_ocean', 'year'), name='tau_y_z0_025_mod',
                        coords=[lat_025_mod, lon_025_mod, year], 
                        dims=['yu_ocean', 'xu_ocean', 'year'])
print(tau_y_z0_025_mod_xr)
tau_y_z0_025_mod_xr.to_netcdf(output_path + 'tau_y_z0_025_mod.nc')

tau_y_z0_025_slope_mod_xr = xr.DataArray(tau_y_z0_025_slope_mod, name='tau_y_z0_025_slope_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_025_slope_mod_xr)
tau_y_z0_025_slope_mod_xr.to_netcdf(output_path + 'tau_y_z0_025_slope_mod.nc')

tau_y_z0_025_p_value_mod_xr = xr.DataArray(tau_y_z0_025_p_value_mod, name='tau_y_z0_025_p_value_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_025_p_value_mod_xr)
tau_y_z0_025_p_value_mod_xr.to_netcdf(output_path + 'tau_y_z0_025_p_value_mod.nc')

tau_y_z0_025_std_err_mod_xr = xr.DataArray(tau_y_z0_025_std_err_mod, name='tau_y_z0_025_std_err_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_025_std_err_mod_xr)
tau_y_z0_025_std_err_mod_xr.to_netcdf(output_path + 'tau_y_z0_025_std_err_mod.nc')



tau_y_z0_01_mod_xr = xr.DataArray(tau_y_z0_01_mod.transpose('yu_ocean', 'xu_ocean', 'year'), name='tau_y_z0_01_mod',
                        coords=[lat_01_mod, lon_01_mod, year], 
                        dims=['yu_ocean', 'xu_ocean', 'year'])
print(tau_y_z0_01_mod_xr)
tau_y_z0_01_mod_xr.to_netcdf(output_path + 'tau_y_z0_01_mod.nc')

tau_y_z0_01_slope_mod_xr = xr.DataArray(tau_y_z0_01_slope_mod, name='tau_y_z0_01_slope_mod',
                        coords=[lat_01_mod, lon_01_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_01_slope_mod_xr)
tau_y_z0_01_slope_mod_xr.to_netcdf(output_path + 'tau_y_z0_01_slope_mod.nc')

tau_y_z0_01_p_value_mod_xr = xr.DataArray(tau_y_z0_01_p_value_mod, name='tau_y_z0_01_p_value_mod',
                        coords=[lat_01_mod, lon_01_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_01_p_value_mod_xr)
tau_y_z0_01_p_value_mod_xr.to_netcdf(output_path + 'tau_y_z0_01_p_value_mod.nc')

tau_y_z0_01_std_err_mod_xr = xr.DataArray(tau_y_z0_01_std_err_mod, name='tau_y_z0_01_std_err_mod',
                        coords=[lat_01_mod, lon_01_mod], 
                        dims=['yu_ocean', 'xu_ocean'])
print(tau_y_z0_01_std_err_mod_xr)
tau_y_z0_01_std_err_mod_xr.to_netcdf(output_path + 'tau_y_z0_01_std_err_mod.nc')

<xarray.DataArray 'tau_y_z0_1_mod' (yu_ocean: 101, xu_ocean: 151, year: 25)>
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,     

<xarray.DataArray 'tau_y_z0_025_p_value_mod' (yu_ocean: 101, xu_ocean: 151)>
array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [0.32550635, 0.45943289, 0.51390507, ..., 0.05588847, 0.96553467,
        0.48481414],
       [0.39474562, 0.58764632, 0.73669702, ...,        nan,        nan,
               nan],
       [0.33188895, 0.66127807, 0.96032365, ..., 0.26851578, 0.17948004,
        0.2032957 ]])
Coordinates:
  * yu_ocean  (yu_ocean) float64 -79.97 -79.02 -77.96 ... 17.95 18.9 20.08
  * xu_ocean  (xu_ocean) float64 140.0 141.0 142.0 143.0 ... 288.0 289.0 290.0
<xarray.DataArray 'tau_y_z0_025_std_err_mod' (yu_ocean: 101, xu_ocean: 151)>
array([[           nan,            nan,            nan, ...,
                   nan,            nan,  