In [1]:
'''
This file plots CMIP5 RCP - HIST over South Australia
/Users/earl/Desktop/Yang
and places the outputs in
/Users/earl/Dropbox/CMIP5/figures

Earl Duran 
created: 19-Mar-18
e.duran@unsw.edu.au
'''

import pandas as pd
import cosima_cookbook as cc
import os
import xarray as xr
import numpy as np
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import matplotlib
import sys
import pickle
import itertools
def find_nearest_index(array, value):
    return int((np.abs(array - value)).argmin())
from scipy import interpolate
from scipy import stats
from dask.distributed import Client

import cartopy.crs as ccrs
import cartopy.feature as cft
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
def arange(start,end,stride=1):
    return np.arange(start,end+0.00000001,stride)

import sys, os
sys.path.append(os.path.join(os.getcwd(), '..'))  # so we can import ../exptdata
import exptdata

session = cc.database.create_session()

In [2]:
%%javascript
IPython.notebook.kernel.execute('nb_name = ' + '"' + IPython.notebook.notebook_name + '"')

<IPython.core.display.Javascript object>

In [3]:
client = Client()
client

<Client: 'tcp://127.0.0.1:46649' processes=4 threads=8, memory=33.67 GB>

In [4]:
input_path = '/g/data/e14/erd561/NOAA_OI_SST_V2/'
output_path = '/g/data/e14/erd561/Australia_8617/'

data = xr.open_dataset(input_path + 'sst.mnmean.nc')

data

<xarray.Dataset>
Dimensions:    (lat: 180, lon: 360, nbnds: 2, time: 447)
Coordinates:
  * lat        (lat) float32 89.5 88.5 87.5 86.5 ... -86.5 -87.5 -88.5 -89.5
  * lon        (lon) float32 0.5 1.5 2.5 3.5 4.5 ... 356.5 357.5 358.5 359.5
  * time       (time) datetime64[ns] 1981-12-01 1982-01-01 ... 2019-02-01
Dimensions without coordinates: nbnds
Data variables:
    sst        (time, lat, lon) float32 ...
    time_bnds  (time, nbnds) datetime64[ns] ...
Attributes:
    title:          NOAA Optimum Interpolation (OI) SST V2
    Conventions:    CF-1.0
    history:        Wed Apr  6 13:47:45 2005: ncks -d time,0,278 SAVEs/sst.mn...
    comments:       Data described in  Reynolds, R.W., N.A. Rayner, T.M.\nSmi...
    platform:       Model
    source:         NCEP Climate Modeling Branch
    institution:    National Centers for Environmental Prediction
    References:     https://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oiss...
    dataset_title:  NOAA Optimum Interpolation (OI) SST V

In [5]:
lonW = 88
lonE = 182

latS = -72
latN = 22

temp_z0 = xr.open_dataset(input_path + 'sst.mnmean.nc').\
                sst.\
                sel(lon=slice(lonW,lonE)).\
                sel(lat=slice(latS,latN,-1)).\
                groupby('time.year').\
                mean('time', skipna=True).sel(year=slice(1986,2017))

temp_z0 = temp_z0.assign_coords(lon=temp_z0.lon)

mask = xr.open_dataset(input_path + 'lsmask.nc').\
                mask.\
                sel(lon=slice(lonW,lonE)).\
                sel(lat=slice(latS,latN,-1))

mask = mask.assign_coords(lon=mask.lon)

temp_z0 = temp_z0.where(mask==1, np.nan)

temp_z0 = temp_z0.squeeze()
print(temp_z0)

<xarray.DataArray 'sst' (year: 32, lat: 94, lon: 94)>
array([[[       nan,        nan,        nan, ..., -1.3924998,
         -1.3499999, -1.3299999],
        [       nan,        nan,        nan, ..., -1.4091667,
         -1.3808333, -1.3675   ],
        [       nan,        nan,        nan, ..., -1.3791666,
         -1.3533334, -1.3449999],
        ...,
        [27.934166 , 27.906668 , 27.888334 , ..., 26.829165 ,
         26.792501 , 26.77333  ],
        [27.737497 , 27.722498 , 27.71     , ..., 26.58583  ,
         26.5475   , 26.530832 ],
        [27.552498 , 27.543333 , 27.485832 , ..., 26.285835 ,
         26.255835 , 26.235    ]],

       [[       nan,        nan,        nan, ..., -1.2883333,
         -1.3733331, -1.4124999],
        [       nan,        nan,        nan, ..., -1.3166667,
         -1.3808333, -1.415    ],
        [       nan,        nan,        nan, ..., -1.2933333,
         -1.3391666, -1.3666667],
        ...,
        [28.167498 , 28.218336 , 28.259165 , ..., 26.6

In [6]:
lat = temp_z0.lat
lon = temp_z0.lon
year = temp_z0.year

# temp_z0_trans = np.transpose(temp_z0, (2,1,0))
temp_z0_trans = temp_z0
print(np.shape(temp_z0_trans))
temp_z0_slope = xr.DataArray(
    np.zeros([np.shape(lat)[0], np.shape(lon)[0]]), dims=(
    'lat', 'lon'), coords=[lat, lon], name='temp_z0')
temp_z0_p_value = xr.DataArray(
    np.zeros([np.shape(lat)[0], np.shape(lon)[0]]), dims=(
    'lat', 'lon'), coords=[lat, lon], name='temp_z0')
temp_z0_std_err = xr.DataArray(
    np.zeros([np.shape(lat)[0], np.shape(lon)[0]]), dims=(
    'lat', 'lon'), coords=[lat, lon], name='temp_z0')
for iid, i in enumerate(lat):
    for jid, j in enumerate(lon):
        temp_z0_slope[jid, iid], _, _, temp_z0_p_value[jid, iid], temp_z0_std_err[jid, iid] = \
        stats.linregress(year, temp_z0_trans[:, jid, iid])
    print('lat ' + str(np.array(i)))
print(temp_z0_slope)

(32, 94, 94)
lat -71.5
lat -70.5
lat -69.5
lat -68.5
lat -67.5
lat -66.5
lat -65.5
lat -64.5
lat -63.5
lat -62.5
lat -61.5
lat -60.5
lat -59.5
lat -58.5
lat -57.5
lat -56.5
lat -55.5
lat -54.5
lat -53.5
lat -52.5
lat -51.5
lat -50.5
lat -49.5
lat -48.5
lat -47.5
lat -46.5
lat -45.5
lat -44.5
lat -43.5
lat -42.5
lat -41.5
lat -40.5
lat -39.5
lat -38.5
lat -37.5
lat -36.5
lat -35.5
lat -34.5
lat -33.5
lat -32.5
lat -31.5
lat -30.5
lat -29.5
lat -28.5
lat -27.5
lat -26.5
lat -25.5
lat -24.5
lat -23.5
lat -22.5
lat -21.5
lat -20.5
lat -19.5
lat -18.5
lat -17.5
lat -16.5
lat -15.5
lat -14.5
lat -13.5
lat -12.5
lat -11.5
lat -10.5
lat -9.5
lat -8.5
lat -7.5
lat -6.5
lat -5.5
lat -4.5
lat -3.5
lat -2.5
lat -1.5
lat -0.5
lat 0.5
lat 1.5
lat 2.5
lat 3.5
lat 4.5
lat 5.5
lat 6.5
lat 7.5
lat 8.5
lat 9.5
lat 10.5
lat 11.5
lat 12.5
lat 13.5
lat 14.5
lat 15.5
lat 16.5
lat 17.5
lat 18.5
lat 19.5
lat 20.5
lat 21.5
<xarray.DataArray 'temp_z0' (lat: 94, lon: 94)>
array([[            nan,             nan,

In [7]:
temp_z0_xr = xr.DataArray(np.transpose(temp_z0.values, (1,2,0)), name='temp_z0_oisst',
                        coords=[lat, lon, year], 
                        dims=['lat', 'lon', 'year'])
print(temp_z0_xr)
temp_z0_xr.to_netcdf(output_path + 'temp_z0_oisst.nc')

temp_z0_slope_xr = xr.DataArray(temp_z0_slope, name='temp_z0_slope_oisst',
                        coords=[lat, lon], 
                        dims=['lat', 'lon'])
print(temp_z0_slope_xr)
temp_z0_slope_xr.to_netcdf(output_path + 'temp_z0_slope_oisst.nc')

temp_z0_p_value_xr = xr.DataArray(temp_z0_p_value, name='temp_z0_p_value_oisst',
                        coords=[lat, lon], 
                        dims=['lat', 'lon'])
print(temp_z0_p_value_xr)
temp_z0_p_value_xr.to_netcdf(output_path + 'temp_z0_p_value_oisst.nc')

temp_z0_std_err_xr = xr.DataArray(temp_z0_std_err, name='temp_z0_std_err_oisst',
                        coords=[lat, lon], 
                        dims=['lat', 'lon'])
print(temp_z0_std_err_xr)
temp_z0_std_err_xr.to_netcdf(output_path + 'temp_z0_std_err_oisst.nc')

<xarray.DataArray 'temp_z0_oisst' (lat: 94, lon: 94, year: 32)>
array([[[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        ...,
        [-1.3924998, -1.2883333, -1.3908333, ..., -1.4874998,
         -1.4291667, -1.3766667],
        [-1.3499999, -1.3733331, -1.4008335, ..., -1.4833332,
         -1.4408334, -1.4025   ],
        [-1.3299999, -1.4124999, -1.4108334, ..., -1.4833335,
         -1.4583334, -1.4016666]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        ...,
        [-1.4091667, -1.3166667, -1.3558334,

In [8]:
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='1deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_z0_1_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='temp').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=0, method='nearest')-273.15
print(temp_z0_1_mod_month)

temp_z0_1_mod_month.load()
print(temp_z0_1_mod_month)

xt_ocean = temp_z0_1_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_z0_1_mod_month = temp_z0_1_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(temp_z0_1_mod_month)

temp_z0_1_mod = temp_z0_1_mod_month.groupby('time.year').mean('time')
print(temp_z0_1_mod)

temp_z0_1_mod = temp_z0_1_mod.sel(year=slice(1986+60*4,2017+60*4))
print(temp_z0_1_mod)

1deg_jra55v13_iaf_spinup1_B1


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'temp' (time: 300, yt_ocean: 160, xt_ocean: 90)>
dask.array<sub, shape=(300, 160, 90), dtype=float32, chunksize=(1, 124, 90), chunktype=numpy.ndarray>
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.63 -69.18 -68.71 ... 17.85 18.59 19.36
  * xt_ocean  (xt_ocean) float64 -269.5 -268.5 -267.5 ... -182.5 -181.5 -180.5
    st_ocean  float64 1.152
  * time      (time) object 1958-07-02 12:00:00 ... 2257-07-02 12:00:00
<xarray.DataArray 'temp' (time: 300, yt_ocean: 160, xt_ocean: 90)>
array([[[       nan,        nan,        nan, ..., -1.3452759,
         -1.3441772, -1.342804 ],
        [       nan,        nan,        nan, ..., -1.3128967,
         -1.3044739, -1.3048401],
        [       nan,        nan,        nan, ..., -1.2649231,
         -1.258606 , -1.2553406],
        ...,
        [27.779205 , 27.703247 , 27.695343 , ..., 26.297943 ,
         26.258667 , 26.213867 ],
        [27.70932  , 27.692932 , 27.660675 , ..., 26.196869 ,
         26.152313 , 26.096619 ],
   

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'temp' (year: 300, yt_ocean: 160, xt_ocean: 90)>
array([[[       nan,        nan,        nan, ..., -1.3452759,
         -1.3441772, -1.342804 ],
        [       nan,        nan,        nan, ..., -1.3128967,
         -1.3044739, -1.3048401],
        [       nan,        nan,        nan, ..., -1.2649231,
         -1.258606 , -1.2553406],
        ...,
        [27.779205 , 27.703247 , 27.695343 , ..., 26.297943 ,
         26.258667 , 26.213867 ],
        [27.70932  , 27.692932 , 27.660675 , ..., 26.196869 ,
         26.152313 , 26.096619 ],
        [27.644135 , 27.584229 , 27.590027 , ..., 26.063538 ,
         26.02304  , 25.974182 ]],

       [[       nan,        nan,        nan, ..., -1.6895447,
         -1.6719666, -1.6455994],
        [       nan,        nan,        nan, ..., -1.6984863,
         -1.6864624, -1.6624451],
        [       nan,        nan,        nan, ..., -1.6994324,
         -1.6943054, -1.6785583],
        ...,
        [27.504333 , 27.451141 , 27.45498

In [9]:
year = temp_z0_1_mod.year
lat_1_mod = temp_z0_1_mod.yt_ocean
lon_1_mod = temp_z0_1_mod.xt_ocean

temp_z0_1_trans_mod = temp_z0_1_mod
print(np.shape(temp_z0_1_trans_mod))
temp_z0_1_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='temp_z0_1')
temp_z0_1_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='temp_z0_1')
temp_z0_1_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_1_mod)[0], np.shape(lon_1_mod)[0]]), dims=(
    'lat_1', 'lon_1'), coords=[lat_1_mod, lon_1_mod], name='temp_z0_1')
for iid, i in enumerate(lat_1_mod):
    for jid, j in enumerate(lon_1_mod):
        temp_z0_1_slope_mod[iid, jid], _, _, temp_z0_1_p_value_mod[iid, jid], temp_z0_1_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_z0_1_trans_mod[:, iid, jid])
    print('lat_1_mod ' + str(np.array(i)))
print(temp_z0_1_slope_mod)

(32, 160, 90)
lat_1_mod -69.6292858330716
lat_1_mod -69.17632154294074
lat_1_mod -68.70935410409521
lat_1_mod -68.22843658249317
lat_1_mod -67.73301847540898
lat_1_mod -67.2232002021303
lat_1_mod -66.69847936238045
lat_1_mod -66.15900514695375
lat_1_mod -65.60432451496254
lat_1_mod -65.03463652231858
lat_1_mod -64.44953841598465
lat_1_mod -63.84927987875662
lat_1_mod -63.233509039251814
lat_1_mod -62.602526632003375
lat_1_mod -61.95603192247815
lat_1_mod -61.29437678205883
lat_1_mod -60.61731152794955
lat_1_mod -59.92523891318751
lat_1_mod -59.21795988186098
lat_1_mod -58.49592747485757
lat_1_mod -57.75899250138302
lat_1_mod -57.00765736171395
lat_1_mod -56.24182163656275
lat_1_mod -55.46203582865502
lat_1_mod -54.66824687203264
lat_1_mod -53.86105179481633
lat_1_mod -53.04044315107174
lat_1_mod -52.20706260764199
lat_1_mod -51.36094630171701
lat_1_mod -50.50277835512628
lat_1_mod -49.63263616124607
lat_1_mod -48.751243830625256
lat_1_mod -47.858717411335334
lat_1_mod -46.9558182702592

In [10]:
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='025deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_z0_025_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='temp').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=0, method='nearest')-273.15
print(temp_z0_025_mod_month)

temp_z0_025_mod_month.load()
print(temp_z0_025_mod_month)

xt_ocean = temp_z0_025_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_z0_025_mod_month = temp_z0_025_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(temp_z0_025_mod_month)

temp_z0_025_mod = temp_z0_025_mod_month.groupby('time.year').mean('time')
print(temp_z0_025_mod)

temp_z0_025_mod = temp_z0_025_mod.sel(year=slice(1986+60*4,2017+60*4))
print(temp_z0_025_mod)

025deg_jra55v13_iaf_gmredi6


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option t

<xarray.DataArray 'temp' (time: 300, yt_ocean: 475, xt_ocean: 360)>
dask.array<sub, shape=(300, 475, 360), dtype=float32, chunksize=(1, 216, 248), chunktype=numpy.ndarray>
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * xt_ocean  (xt_ocean) float64 -269.9 -269.6 -269.4 ... -180.6 -180.4 -180.1
    st_ocean  float64 1.152
  * time      (time) object 1958-06-30 12:00:00 ... 2257-06-30 12:00:00
<xarray.DataArray 'temp' (time: 300, yt_ocean: 475, xt_ocean: 360)>
array([[[       nan,        nan,        nan, ..., -1.3691101,
         -1.3626709, -1.355896 ],
        [       nan,        nan,        nan, ..., -1.3651428,
         -1.3577881, -1.3512878],
        [       nan,        nan,        nan, ..., -1.3556519,
         -1.3484192, -1.3435669],
        ...,
        [27.802582 , 27.755707 , 27.710144 , ..., 25.934357 ,
         25.9169   , 25.897644 ],
        [27.709442 , 27.649994 , 27.596466 , ..., 25.882812 ,
         25.862396 , 25.845978 ],

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'temp' (year: 300, yt_ocean: 475, xt_ocean: 360)>
array([[[       nan,        nan,        nan, ..., -1.3691101,
         -1.3626709, -1.355896 ],
        [       nan,        nan,        nan, ..., -1.3651428,
         -1.3577881, -1.3512878],
        [       nan,        nan,        nan, ..., -1.3556519,
         -1.3484192, -1.3435669],
        ...,
        [27.802582 , 27.755707 , 27.710144 , ..., 25.934357 ,
         25.9169   , 25.897644 ],
        [27.709442 , 27.649994 , 27.596466 , ..., 25.882812 ,
         25.862396 , 25.845978 ],
        [27.600006 , 27.545258 , 27.514069 , ..., 25.834686 ,
         25.809082 , 25.799255 ]],

       [[       nan,        nan,        nan, ..., -1.6878967,
         -1.6752625, -1.658081 ],
        [       nan,        nan,        nan, ..., -1.6947937,
         -1.6841736, -1.6699829],
        [       nan,        nan,        nan, ..., -1.6965942,
         -1.6852722, -1.6719666],
        ...,
        [27.432068 , 27.406036 , 27.3960

In [11]:
lat_025_mod = temp_z0_025_mod.yt_ocean
lon_025_mod = temp_z0_025_mod.xt_ocean

temp_z0_025_trans_mod = temp_z0_025_mod
print(np.shape(temp_z0_025_trans_mod))
temp_z0_025_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='temp_z0_025')
temp_z0_025_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='temp_z0_025')
temp_z0_025_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_025_mod)[0], np.shape(lon_025_mod)[0]]), dims=(
    'lat_025', 'lon_025'), coords=[lat_025_mod, lon_025_mod], name='temp_z0_025')
for iid, i in enumerate(lat_025_mod):
    for jid, j in enumerate(lon_025_mod):
        temp_z0_025_slope_mod[iid, jid], _, _, temp_z0_025_p_value_mod[iid, jid], temp_z0_025_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_z0_025_trans_mod[:, iid, jid])
    print('lat_025_mod ' + str(np.array(i)))
print(temp_z0_025_slope_mod)

(32, 475, 360)
lat_025_mod -69.98914896732052
lat_025_mod -69.8835503781156
lat_025_mod -69.77795178891068
lat_025_mod -69.67235319970577
lat_025_mod -69.56675461050085
lat_025_mod -69.46115602129593
lat_025_mod -69.35555743209102
lat_025_mod -69.2499588428861
lat_025_mod -69.14436025368119
lat_025_mod -69.03876166447627
lat_025_mod -68.93316307527135
lat_025_mod -68.82756448606644
lat_025_mod -68.72196589686152
lat_025_mod -68.6163673076566
lat_025_mod -68.51076871845169
lat_025_mod -68.40517012924677
lat_025_mod -68.29957154004185
lat_025_mod -68.19397295083694
lat_025_mod -68.08837436163202
lat_025_mod -67.9827757724271
lat_025_mod -67.87717718322219
lat_025_mod -67.77157859401727
lat_025_mod -67.66598000481235
lat_025_mod -67.56038141560744
lat_025_mod -67.45478282640252
lat_025_mod -67.3491842371976
lat_025_mod -67.24358564799269
lat_025_mod -67.13798705878777
lat_025_mod -67.03238846958286
lat_025_mod -66.92678988037794
lat_025_mod -66.82119129117302
lat_025_mod -66.7155927019681

lat_025_mod -30.778202070190314
lat_025_mod -30.56317292803898
lat_025_mod -30.34766755148325
lat_025_mod -30.131685174432455
lat_025_mod -29.915230577717967
lat_025_mod -29.698303070212805
lat_025_mod -29.480907483686703
lat_025_mod -29.2630432019257
lat_025_mod -29.044715107989248
lat_025_mod -28.82592266049411
lat_025_mod -28.606670794106993
lat_025_mod -28.38695904216067
lat_025_mod -28.166792391212045
lat_025_mod -27.946170449161986
lat_025_mod -27.72509825470525
lat_025_mod -27.50357549012893
lat_025_mod -27.28160724647727
lat_025_mod -27.059193280207044
lat_025_mod -26.83633873488693
lat_025_mod -26.61304344089147
lat_025_mod -26.389312594451354
lat_025_mod -26.165146099570944
lat_025_mod -25.940549205242547
lat_025_mod -25.715521888775697
lat_025_mod -25.490069451985352
lat_025_mod -25.264191945124278
lat_025_mod -25.037894722851966
lat_025_mod -24.811177907964588
lat_025_mod -24.58404690794839
lat_025_mod -24.356501917704698
lat_025_mod -24.12854839748857
lat_025_mod -23.90018

In [12]:
latS = -70
latN = 20
lonW = 90-360
lonE = 180-360
ekey='01deg'
expt = exptdata.exptdict[ekey]['expt']
print(expt)

temp_z0_01_mod_month = cc.querying.getvar(expt=expt,
                                     session=session,
                                     ncfile='ocean.nc',
                                     variable='temp').\
sel(yt_ocean=slice(latS,latN)).\
sel(xt_ocean=slice(lonW,lonE)).\
sel(st_ocean=0, method='nearest')-273.15
print(temp_z0_01_mod_month)

temp_z0_01_mod_month.load()
print(temp_z0_01_mod_month)

xt_ocean = temp_z0_01_mod_month.xt_ocean
xt_ocean_corrected = xt_ocean + 360
temp_z0_01_mod_month = temp_z0_01_mod_month.assign_coords(xt_ocean=xt_ocean_corrected)
print(temp_z0_01_mod_month)

temp_z0_01_mod = temp_z0_01_mod_month.groupby('time.year').mean('time')
print(temp_z0_01_mod)

temp_z0_01_mod = temp_z0_01_mod.sel(year=slice(1986,2017))
print(temp_z0_01_mod)

01deg_jra55v13_iaf


/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cosima_cookbook/querying.py:96: FutureWarning: In xarray version 0.14 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  preprocess=lambda d: d[variable].to_dataset() if variable not in d.coords else d)


<xarray.DataArray 'temp' (time: 396, yt_ocean: 1186, xt_ocean: 900)>
dask.array<sub, shape=(396, 1186, 900), dtype=float32, chunksize=(1, 300, 400), chunktype=numpy.ndarray>
Coordinates:
  * yt_ocean  (yt_ocean) float64 -70.0 -69.96 -69.92 ... 19.75 19.84 19.94
  * xt_ocean  (xt_ocean) float64 -269.9 -269.8 -269.7 ... -180.2 -180.1 -180.0
    st_ocean  float64 0.5413
  * time      (time) object 1985-01-14 12:00:00 ... 2017-12-14 12:00:00
<xarray.DataArray 'temp' (time: 396, yt_ocean: 1186, xt_ocean: 900)>
array([[[       nan,        nan,        nan, ..., -1.6495056,
         -1.6503601, -1.6513062],
        [       nan,        nan,        nan, ..., -1.647522 ,
         -1.6482849, -1.6491699],
        [       nan,        nan,        nan, ..., -1.6450806,
         -1.6460876, -1.6468506],
        ...,
        [25.293152 , 25.223358 , 25.163635 , ..., 25.029602 ,
         25.062805 , 25.099335 ],
        [25.10736  , 25.045837 , 24.992981 , ..., 25.03833  ,
         25.077118 , 25.118774

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/backends/api.py:934: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  from_openmfds=True,
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.DataArray 'temp' (year: 33, yt_ocean: 1186, xt_ocean: 900)>
array([[[       nan,        nan,        nan, ..., -1.7491251,
         -1.7482351, -1.7479095],
        [       nan,        nan,        nan, ..., -1.7536646,
         -1.7519506, -1.7504578],
        [       nan,        nan,        nan, ..., -1.757871 ,
         -1.7560654, -1.7536036],
        ...,
        [27.634636 , 27.625414 , 27.618845 , ..., 26.017271 ,
         26.008379 , 26.005022 ],
        [27.61979  , 27.614256 , 27.60399  , ..., 26.008963 ,
         26.004587 , 25.99981  ],
        [27.59926  , 27.58808  , 27.559431 , ..., 26.000448 ,
         26.000229 , 25.996185 ]],

       [[       nan,        nan,        nan, ..., -1.6110916,
         -1.6088562, -1.6058298],
        [       nan,        nan,        nan, ..., -1.6142935,
         -1.6126913, -1.610583 ],
        [       nan,        nan,        nan, ..., -1.616633 ,
         -1.6149164, -1.613645 ],
        ...,
        [27.499376 , 27.499647 , 27.4988

In [13]:
lat_01_mod = temp_z0_01_mod.yt_ocean
lon_01_mod = temp_z0_01_mod.xt_ocean

temp_z0_01_trans_mod = temp_z0_01_mod
print(np.shape(temp_z0_01_trans_mod))
temp_z0_01_slope_mod = xr.DataArray(
    np.zeros([np.shape(lat_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'lat_01', 'lon_01'), coords=[lat_01_mod, lon_01_mod], name='temp_z0_01')
temp_z0_01_p_value_mod = xr.DataArray(
    np.zeros([np.shape(lat_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'lat_01', 'lon_01'), coords=[lat_01_mod, lon_01_mod], name='temp_z0_01')
temp_z0_01_std_err_mod = xr.DataArray(
    np.zeros([np.shape(lat_01_mod)[0], np.shape(lon_01_mod)[0]]), dims=(
    'lat_01', 'lon_01'), coords=[lat_01_mod, lon_01_mod], name='temp_z0_01')
for iid, i in enumerate(lat_01_mod):
    for jid, j in enumerate(lon_01_mod):
        temp_z0_01_slope_mod[iid, jid], _, _, temp_z0_01_p_value_mod[iid, jid], temp_z0_01_std_err_mod[iid, jid] = \
        stats.linregress(year, temp_z0_01_trans_mod[:, iid, jid])
    print('lat_01_mod ' + str(np.array(i)))
print(temp_z0_01_slope_mod)

(32, 1186, 900)
lat_01_mod -69.99968147628742
lat_01_mod -69.95744212190694
lat_01_mod -69.91520276752645
lat_01_mod -69.87296341314597
lat_01_mod -69.83072405876548
lat_01_mod -69.788484704385
lat_01_mod -69.74624535000451
lat_01_mod -69.70400599562403
lat_01_mod -69.66176664124355
lat_01_mod -69.61952728686306
lat_01_mod -69.57728793248258
lat_01_mod -69.53504857810209
lat_01_mod -69.49280922372161
lat_01_mod -69.45056986934112
lat_01_mod -69.40833051496064
lat_01_mod -69.36609116058015
lat_01_mod -69.32385180619967
lat_01_mod -69.28161245181919
lat_01_mod -69.2393730974387
lat_01_mod -69.19713374305822
lat_01_mod -69.15489438867773
lat_01_mod -69.11265503429725
lat_01_mod -69.07041567991676
lat_01_mod -69.02817632553628
lat_01_mod -68.9859369711558
lat_01_mod -68.94369761677531
lat_01_mod -68.90145826239483
lat_01_mod -68.85921890801434
lat_01_mod -68.81697955363386
lat_01_mod -68.77474019925337
lat_01_mod -68.73250084487289
lat_01_mod -68.6902614904924
lat_01_mod -68.64802213611192

lat_01_mod -57.61555410415017
lat_01_mod -57.561954948283415
lat_01_mod -57.50827664011144
lat_01_mod -57.45451939409348
lat_01_mod -57.40068285779298
lat_01_mod -57.34676724518897
lat_01_mod -57.292772205033636
lat_01_mod -57.238697950834805
lat_01_mod -57.184544132535514
lat_01_mod -57.13031096318144
lat_01_mod -57.07599809390864
lat_01_mod -57.02160573730968
lat_01_mod -56.9671335457159
lat_01_mod -56.91258173127584
lat_01_mod -56.85794994751838
lat_01_mod -56.80323840615713
lat_01_mod -56.74844676192083
lat_01_mod -56.69357522609733
lat_01_mod -56.6386234546176
lat_01_mod -56.583591658352866
lat_01_mod -56.52847949443875
lat_01_mod -56.47328717333905
lat_01_mod -56.4180143533965
lat_01_mod -56.3626612446767
lat_01_mod -56.307227506731984
lat_01_mod -56.251713349239004
lat_01_mod -56.196118432962265
lat_01_mod -56.14044296719873
lat_01_mod -56.08468661392767
lat_01_mod -56.02884958207567
lat_01_mod -55.972931534839404
lat_01_mod -55.9169326807844
lat_01_mod -55.86085268432745
lat_01

lat_01_mod -39.95288117846647
lat_01_mod -39.87618099040512
lat_01_mod -39.79939482865696
lat_01_mod -39.722522933497494
lat_01_mod -39.64556514937795
lat_01_mod -39.56852171746229
lat_01_mod -39.49139248397716
lat_01_mod -39.414177690984324
lat_01_mod -39.33687718649035
lat_01_mod -39.25949121346409
lat_01_mod -39.18201962169648
lat_01_mod -39.10446265507271
lat_01_mod -39.026820165172495
lat_01_mod -38.94909239680651
lat_01_mod -38.87127920334764
lat_01_mod -38.79338083054117
lat_01_mod -38.71539713355743
lat_01_mod -38.6373283590854
lat_01_mod -38.55917436409714
lat_01_mod -38.480935396234294
lat_01_mod -38.402611314274864
lat_01_mod -38.32420236682212
lat_01_mod -38.24570841446415
lat_01_mod -38.16712970677471
lat_01_mod -38.0884661061561
lat_01_mod -38.00971786316136
lat_01_mod -37.93088484201106
lat_01_mod -37.851967294246286
lat_01_mod -37.772965085909846
lat_01_mod -37.693878469539534
lat_01_mod -37.61470731300435
lat_01_mod -37.53545186984742
lat_01_mod -37.45611200976781
lat_

lat_01_mod -16.42049687015551
lat_01_mod -16.32455195620721
lat_01_mod -16.228559883221106
lat_01_mod -16.13252105633506
lat_01_mod -16.036435564073468
lat_01_mod -15.940303812710189
lat_01_mod -15.84412589220787
lat_01_mod -15.747902209967636
lat_01_mod -15.651632857377699
lat_01_mod -15.555318242957538
lat_01_mod -15.458958459508088
lat_01_mod -15.36255391665811
lat_01_mod -15.26610470860825
lat_01_mod -15.16961124608732
lat_01_mod -15.073073624682506
lat_01_mod -14.976492256213264
lat_01_mod -14.879867237639997
lat_01_mod -14.783198981863242
lat_01_mod -14.686487587203125
lat_01_mod -14.589733467631538
lat_01_mod -14.492936722814687
lat_01_mod -14.39609776778593
lat_01_mod -14.299216703543747
lat_01_mod -14.202293946172919
lat_01_mod -14.10532959799024
lat_01_mod -14.008324076121701
lat_01_mod -13.911277484188298
lat_01_mod -13.814190240346873
lat_01_mod -13.71706244950835
lat_01_mod -13.6198945308499
lat_01_mod -13.522686590557955
lat_01_mod -13.425439048819337
lat_01_mod -13.32815

lat_01_mod 10.785733218933103
lat_01_mod 10.883950603275439
lat_01_mod 10.982135547454417
lat_01_mod 11.080287929023381
lat_01_mod 11.178407315709944
lat_01_mod 11.27649358612572
lat_01_mod 11.374546308855647
lat_01_mod 11.47256536358603
lat_01_mod 11.570550319771696
lat_01_mod 11.668501058189939
lat_01_mod 11.766417149177911
lat_01_mod 11.864298474620044
lat_01_mod 11.962144605748115
lat_01_mod 12.059955425569713
lat_01_mod 12.157730506223396
lat_01_mod 12.25546973185579
lat_01_mod 12.35317267552425
lat_01_mod 12.450839222530183
lat_01_mod 12.548468946861613
lat_01_mod 12.646061734990322
lat_01_mod 12.743617161846737
lat_01_mod 12.841135115088473
lat_01_mod 12.938615170599938
lat_01_mod 13.036057217239895
lat_01_mod 13.133460831858166
lat_01_mod 13.230825904529832
lat_01_mod 13.328152013081416
lat_01_mod 13.425439048819337
lat_01_mod 13.522686590557955
lat_01_mod 13.6198945308499
lat_01_mod 13.71706244950835
lat_01_mod 13.814190240346873
lat_01_mod 13.911277484188298
lat_01_mod 14.008

In [14]:
temp_z0_1_mod_xr = xr.DataArray(temp_z0_1_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='temp_z0_1_mod',
                        coords=[lat_1_mod, lon_1_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(temp_z0_1_mod_xr)
temp_z0_1_mod_xr.to_netcdf(output_path + 'temp_z0_1_mod.nc')

temp_z0_1_slope_mod_xr = xr.DataArray(temp_z0_1_slope_mod, name='temp_z0_1_slope_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_1_slope_mod_xr)
temp_z0_1_slope_mod_xr.to_netcdf(output_path + 'temp_z0_1_slope_mod.nc')

temp_z0_1_p_value_mod_xr = xr.DataArray(temp_z0_1_p_value_mod, name='temp_z0_1_p_value_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_1_p_value_mod_xr)
temp_z0_1_p_value_mod_xr.to_netcdf(output_path + 'temp_z0_1_p_value_mod.nc')

temp_z0_1_std_err_mod_xr = xr.DataArray(temp_z0_1_std_err_mod, name='temp_z0_1_std_err_mod',
                        coords=[lat_1_mod, lon_1_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_1_std_err_mod_xr)
temp_z0_1_std_err_mod_xr.to_netcdf(output_path + 'temp_z0_1_std_err_mod.nc')



temp_z0_025_mod_xr = xr.DataArray(temp_z0_025_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='temp_z0_025_mod',
                        coords=[lat_025_mod, lon_025_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(temp_z0_025_mod_xr)
temp_z0_025_mod_xr.to_netcdf(output_path + 'temp_z0_025_mod.nc')

temp_z0_025_slope_mod_xr = xr.DataArray(temp_z0_025_slope_mod, name='temp_z0_025_slope_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_025_slope_mod_xr)
temp_z0_025_slope_mod_xr.to_netcdf(output_path + 'temp_z0_025_slope_mod.nc')

temp_z0_025_p_value_mod_xr = xr.DataArray(temp_z0_025_p_value_mod, name='temp_z0_025_p_value_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_025_p_value_mod_xr)
temp_z0_025_p_value_mod_xr.to_netcdf(output_path + 'temp_z0_025_p_value_mod.nc')

temp_z0_025_std_err_mod_xr = xr.DataArray(temp_z0_025_std_err_mod, name='temp_z0_025_std_err_mod',
                        coords=[lat_025_mod, lon_025_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_025_std_err_mod_xr)
temp_z0_025_std_err_mod_xr.to_netcdf(output_path + 'temp_z0_025_std_err_mod.nc')



temp_z0_01_mod_xr = xr.DataArray(temp_z0_01_mod.transpose('yt_ocean', 'xt_ocean', 'year'), name='temp_z0_01_mod',
                        coords=[lat_01_mod, lon_01_mod, year], 
                        dims=['yt_ocean', 'xt_ocean', 'year'])
print(temp_z0_01_mod_xr)
temp_z0_01_mod_xr.to_netcdf(output_path + 'temp_z0_01_mod.nc')

temp_z0_01_slope_mod_xr = xr.DataArray(temp_z0_01_slope_mod, name='temp_z0_01_slope_mod',
                        coords=[lat_01_mod, lon_01_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_01_slope_mod_xr)
temp_z0_01_slope_mod_xr.to_netcdf(output_path + 'temp_z0_01_slope_mod.nc')

temp_z0_01_p_value_mod_xr = xr.DataArray(temp_z0_01_p_value_mod, name='temp_z0_01_p_value_mod',
                        coords=[lat_01_mod, lon_01_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_01_p_value_mod_xr)
temp_z0_01_p_value_mod_xr.to_netcdf(output_path + 'temp_z0_01_p_value_mod.nc')

temp_z0_01_std_err_mod_xr = xr.DataArray(temp_z0_01_std_err_mod, name='temp_z0_01_std_err_mod',
                        coords=[lat_01_mod, lon_01_mod], 
                        dims=['yt_ocean', 'xt_ocean'])
print(temp_z0_01_std_err_mod_xr)
temp_z0_01_std_err_mod_xr.to_netcdf(output_path + 'temp_z0_01_std_err_mod.nc')

<xarray.DataArray 'temp_z0_1_mod' (yt_ocean: 160, xt_ocean: 90, year: 32)>
array([[[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        ...,
        [-1.7013855, -1.3687439, -1.7966309, ..., -1.7720337,
         -1.6766357, -1.5481567],
        [-1.7080078, -1.3595276, -1.7927551, ..., -1.7737122,
         -1.6951599, -1.5387268],
        [-1.7178955, -1.357666 , -1.7877197, ..., -1.7743225,
         -1.7155151, -1.525177 ]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        ...,
        [-1.6648254, -1.3642883, 

<xarray.DataArray 'temp_z0_025_slope_mod' (yt_ocean: 475, xt_ocean: 360)>
array([[        nan,         nan,         nan, ..., -0.00260196,
        -0.00262116, -0.00265713],
       [        nan,         nan,         nan, ..., -0.0026768 ,
        -0.00271443, -0.00277172],
       [        nan,         nan,         nan, ..., -0.00280763,
        -0.00288257, -0.00295588],
       ...,
       [ 0.00741117,  0.00661849,  0.00675047, ...,  0.02075295,
         0.0206866 ,  0.02055757],
       [ 0.00727892,  0.0067997 ,  0.00680628, ...,  0.02073461,
         0.02068577,  0.0205974 ],
       [ 0.0071845 ,  0.00638425,  0.00653295, ...,  0.02065114,
         0.02064398,  0.02052996]])
Coordinates:
  * yt_ocean  (yt_ocean) float64 -69.99 -69.88 -69.78 ... 19.49 19.72 19.96
  * xt_ocean  (xt_ocean) float64 90.12 90.38 90.62 90.88 ... 179.4 179.6 179.9
<xarray.DataArray 'temp_z0_025_p_value_mod' (yt_ocean: 475, xt_ocean: 360)>
array([[           nan,            nan,            nan, ...,
        